### ISSUE TITLE
"Actual Grant Submission Date" is not correct

### ISSUE THREAD

**Issue by krobasky** [RENCI/ctmd#105]
Examples:
Kids Mod Pah, PID=49, has no grant date on the dashboard, but should have
Intro JIA, PID=51, has grant date but should not have

**Comment by xu-hao** [comment]
I just noticed that the version of the docker image is 0.2.4. The latest version 0.2.11.
________________________________

**Comment by xu-hao** [comment]
After updating to the latest version of the pipeline, 49 has dateSubmitted, 51 has dateSubmitted. The source data has dateSubmitted.

**Comment by krobasky** [comment]
@xu-hao 51 looks good, but I still don’t see “actual grant submission date” for 49. I’m looking on the pmd-stage.renci.org dashboard, should I be looking somewhere else?

**Comment by xu-hao** [comment]
@krobasky Sorry, i was looking at submission date, actual grant submission data is not available for 51 in the source data mapped from `pro_time_date_2`.

**Comment by xu-hao** [comment]
there is another field `actual_date` which has value for 49.

**Comment by xu-hao** [comment]
@rajshruti18 will update mapping to `actual_date`

**Comment by krobasky** [comment]
@xu-hao can you follow-up to be sure these changes get deployed to the pmd-stage server, and log a comment here so I can check the new Q3 results and close the ticket?

Recall Q3: "Can we get same info out of the dashboard as is included in the attached slides?" where the slides came from THeresa. Thanks!

**Comment by rajshruti18** [comment]
@xu-hao I updated the mapping to actual_date

**Comment by xu-hao** [comment]
@krobasky it's updated @rajshruti18  thanks!

**Comment by krobasky** [comment]
tested fixed
