### ISSUE TITLE
Deploy CTSAs to stage-pmd

### ISSUE THREAD

**Issue by krobasky** [RENCI/ctmd#107]
The PL's would like to sort the proposals by CTSA, but I'm not sure which of the "submitting institutions" are actually CTSAs. Add a column to the proposals table? Also, deploy the CTSA table so it can be viewed here.

**Comment by mbwatson** [comment]
yes i suppose that seems like a viable solution. proposals table can have a column for ctsa id that references CTSAs in the CTSAs table. @xu-hao does this seem like a good idea?

**Comment by mbwatson** [comment]
i'm waiting on an updated list of studies' sites with their CTSAs identified
