### ISSUE TITLE
Ensure submitting institution proposal numbers match Q3 info

### ISSUE THREAD

**Issue by krobasky** [RENCI/ctmd#109]
CTSA missing: Medical University of South Carolina

This CTSA should be represented with 2 submitted proposals but seems to be missing from the dashboard at stage-pmd.renci.org

**Comment by krobasky** [comment]
Please feel free to reassign as appropriate

**Comment by krobasky** [comment]
This ticket is pertaining to the following data received for Q3, and the ticket can be closed when the data from the ctmd matches that in this figure (or can be explained why or why not)

![image](https://user-images.githubusercontent.com/413166/66083426-48937d00-e53a-11e9-91c3-0b40d6732e47.png)

**Comment by krobasky** [comment]
As of today, here's what we have.
MUSC is there but with no proposals (the Vandy chart above shows 2 proposals).

![image](https://user-images.githubusercontent.com/413166/66083768-01f25280-e53b-11e9-9bc9-8a6883e85bdc.png)

**Comment by krobasky** [comment]
@xu-hao this issue was inspired by the fact that we need to either match the Q3 numbers or explain why they don't; hence I've changed the issue title.

I'm counting on you to lead this to a solution, but there's a better solutions leader, please ask the new leader to accept the responsibility and reassign. 

I can help get it reassigned if needed, just let me know.

**Comment by xu-hao** [comment]
we gave the 3 proposals without org_name to teresa and she said she will ask redcap people about it

**Comment by krobasky** [comment]
@rajshruti18 It sounds like this is more about communicating and modelling the data than it is about fixing bugs, so I've reassigned to you. Please contact me with any questions.

This issue was inspired by the fact that we need to either match the Q3 numbers or explain why they don't; hence I've changed the issue title.

I'm counting on you to lead this to a solution, but there's a better solutions leader, please ask the new leader to accept the responsibility and reassign.

**Comment by rajshruti18** [comment]
@krobasky I have no problem taking lead on this issue.

**Comment by dcarsey** [comment]
submitting institutions for some proposals are still needed from theresa

**Comment by rajshruti18** [comment]
Theresa still has 'Medical University of South Carolina' on her plate. She is working on finding out the proposal submitted by 'Medical University of South Carolina'.

**Comment by rajshruti18** [comment]
Still haven't heard back from Theresa.
