### ISSUE TITLE
Add "funded" status, amount, mechanism and NIH project as columns to the proposal table

### ISSUE THREAD

**Issue by krobasky** [RENCI/ctmd#112]
PLs want to be able to group by funded status, and other funding-related items. Please add the funding status that's currently on the 'Proposal Details' as an optional column on the table. Do the same for amount, funding mechanism, and NIH project if those data are available.
related (duplicate?) #118

**Comment by mbwatson** [comment]
what are the funding statuses--_funded,_ _submitted but not yet awarded,_ and not _submitted for funding_?
