### ISSUE TITLE
Why doesn't Vanderbilt have 'Other' universities represented?

### ISSUE THREAD

**Issue by krobasky** [RENCI/ctmd#116]
We filter out proposals that the PI withdrew, so occasionally we will have one less proposal from a submitting insitution.
We may have more updated info than the Vanderbilt report, so occasionally there will be one more.
However, we have nothing from South Carolina we also have 3 proposals with no submitting  institution, 2 of those have PIs located at SC (pid 212, 534); however 'SC' is in insitution_pdf in the raw data.
There are also 16 'Other' institutes. 
What is the meaning of institution_pdf? how would you like us to visualize it, and also the 'Other situtions'?

**Comment by rajshruti18** [comment]
Other Institues- has all the institutes that are not CTSAs

**Comment by rajshruti18** [comment]
Theresa will look into the three proposals (# 212, 247, 534) with no submitting institution and try to get it fixed on the front-end.

**Comment by rajshruti18** [comment]
Theresa is still working on the above issue.
'institution_pdf' should not be used for querying purposes; continue using 'org_name' for finding out submitting institution (Theresa). 'other_organization' has all the institutes' name which are not CTSA Hub (org_name).

**Comment by rajshruti18** [comment]
Still haven't heard back from Theresa.

**Comment by dcarsey** [comment]
From Kyle to Michelle:

How are they mapping the institution IDs to begin with? Currently the API doesn’t output the org mapping when you export the metadata. I think they must have manually keyed them in or set up some sort of mapping on their system. If that’s the case, then as we add institutions, they’ll need to update their list.

**Comment by xu-hao** [comment]
Current this is done by looking at ctsas in the metadata. So we only get org name for ctsas. But this is done automatically.

**Comment by dcarsey** [comment]
CTSA number for Medical University of South Carolina is 79, but the SQL in TIN had it as 76.
Upon further checking at Vanderbilt, TIN uses the SQL field and the South Carolina submissions display accurately, so we need Matt & Kyle to look at this together.  Likely a 10 minute discussion OR an email conversation.
