### ISSUE TITLE
What is the meaning of the categories in the Vandy histogram?

### ISSUE THREAD

**Issue by krobasky** [RENCI/ctmd#117]
?  Initial Consultation
?  Comprehensive Consultation
A  Recruitment Materials
R  Feasibility Assessment (Recruitment Feasibility Assessment)
R  R&R Plan (Recruitment & Retention Planning)
R Community Engagement
A Cohort Discovery (EHR-Based Cohort Assessment?)
R  Standard Agreements
R  SIRB

Also what is 'funded post-submission', per the dashboard?

**Comment by xu-hao** [comment]
whether it is funded when it's submitted
funded
funded post-submission
