### ISSUE TITLE
Need more columns on the proposal table

### ISSUE THREAD

**Issue by krobasky** [RENCI/ctmd#118]
Can we add the option to include the following columns:
- All the resource types, with 'R' for requeted, 'A' for approved and '' for neither; these are including:
-- Recruitment Materials
-- Feasibility Assessment (maps to resource type "Recruitment Feasibility Assessment")
-- R&R Plan (maps to resrouce type "Recruitment & Retention Planning")
-- Community Engagement
-- Cohort Discovery (maps to resource type EHR-Based Cohort Assessment)
-- Standard Agreements
-- SIRB
- funding fields:
-- Approval Funding status
-- Application status

Related to (duplicate?) #112

**Comment by LauraCapps** [comment]
Related to #112

**Comment by mbwatson** [comment]
half done. the flag for comp. cons. approval to the table -- this completed the related #97.

**Comment by mbwatson** [comment]
added columns for each resource, indicating request, approval, or neither.

up next: funding status
