### ISSUE TITLE
Confirm meaning of the terms in 'Q1' AND Answer it

### ISSUE THREAD

**Issue by krobasky** [RENCI/ctmd#119]
'100 initial consultations' - are we starting from 2016? What gets filtered out? Are they just ordered by proposal id?

'applications submitted' - which column in the proposals table tells us that the application has been submitted?

'received funding' - should there just be the 3 funded studies? Because I know the "answers" included well over 3 for 'received funding'

'pending review' - where might we find that information on the proposal table?

'received resources' - is that the same as 'resources approved'?

**Comment by mbwatson** [comment]
- 100 initial consultations - yes, from 10/2016. filtering? only considering those receiving initial consultation. `id`s _do_ jump around. may be six months between submission and consult
- application submitted is actual grant submission
- received funding is grant award date
- pending review: is they have a grant submitted but not awarded
- received resources is resources approved

**Comment by krobasky** [comment]
Here's the slide for Q1

So I assume that means that 'application submitted'/'actual grant submitted' is the union of all 3 items below it:
* 'pending review'='grant submitted by not awarded'
* 'did not receive funding'
* 'received funding'

@davidborland can we add funding status to the sanky diagram between TIC and 'status'? Then we can answer this question while also providing insights around what kinds of therapeutic areas are getting funding, etc. Can we also give the option to remove layers from the Sankey? for example, most of the time, we probably don't need to see the PI. If this sounds reasonable, could you 1) create a ticket, 2) assign it to yourself and 3) label it as phase 2, as you see fit and are able?

![image](https://user-images.githubusercontent.com/413166/66082340-eb96c780-e537-11e9-9eee-f616cb0dd708.png)

**Comment by krobasky** [comment]
@mbwatson I'll leave this assigned to you because if you're able to add the funding and resources columns per #118 (and I see you've already added the feature to list ALL rows), then we should be able to answer Q1 without the Sankey.

**Comment by krobasky** [comment]
I just realized the issue didn't include answering the query - added it to the title.

**Comment by dcarsey** [comment]
Q1 - needs actual start date = fundingstart
 Table name = proposalfunding

**Comment by mbwatson** [comment]
@rajshruti18 @xu-hao To address the "with Study Design" piece of that query, we need to get the Consult_Options into the mapping and pipeline

**Comment by rajshruti18** [comment]
@mbwatson @xu-hao Added 'consult_options' to the mapping.

**Comment by xu-hao** [comment]
looks like we hit a spark bug: https://issues.apache.org/jira/browse/SPARK-25150

**Comment by krobasky** [comment]
@xu-hao what is the symptom of the bug on TIC? Also, do you have a work-around?

**Comment by xu-hao** [comment]
Have workaround

**Comment by xu-hao** [comment]
Bug sympton is the same error message

**Comment by xu-hao** [comment]
I've implemented the workaround, and the pipeline is working correctly now

**Comment by rajshruti18** [comment]
Answers to this query:

1. Go to the 'Proposals' page on the dashboard--->Select ID, Proposal Name and Resource Application Status columns--->Filter 'Resource Application Status' column for 'Initial Consult Ongoing'--->Export results as csv
2. Go to the 'Proposals' page on the dashboard--->Select ID, Proposal Name and Funding Status columns--->Filter 'Funding Status' by 'Application Submitted-Under Review'--->Export results as csv--->Go to the dashboard again, repeat the process and filter by 'Funded'--->Export as csv
3. Go to the 'Proposals' page on the dashboard--->Select ID, Proposal Name and Funding Status columns--->Filter 'Funding Status' by 'Funded'--->Export results as csv
4. Go to the 'Proposals' page on the dashboard--->Select ID, Proposal Name and Funding Status columns--->Filter 'Funding Status' by 'Application Submitted-Under Review'--->Export results as csv
5. Go to the 'Proposals' page on the dashboard--->Select ID, Proposal Name and following columns(respectively):
 ![image](https://user-images.githubusercontent.com/47569410/68599739-1c3f1a80-046f-11ea-926b-e44734d28424.png)--->Filter the results where the column value is 'Approved' and export as csv (respectively)--->Go to the proposals page again--->Select ID, Proposal Name and Approved for Comprehensive Consultation columns--->Export as csv--->Filter out blank column values

**Comment by rajshruti18** [comment]
@mbwatson and @krobasky Please go through the answer I provided for this query and let me know if it looks correct.

**Comment by mbwatson** [comment]
@rajshruti18 so can we close this issue?

**Comment by rajshruti18** [comment]
@mbwatson Yes
