### ISSUE TITLE
Answer Q2

### ISSUE THREAD

**Issue by krobasky** [RENCI/ctmd#120]
Q2:  Of the proposals that were ‘approved for comprehensive consult’, what are the projected and actual dates for the grant and for funding (4 dates)?

**Comment by krobasky** [comment]
Matt, is this question clear, and if so, can the dashboard answer it?

**Comment by mbwatson** [comment]
Yes, the question is clear.
No, the dashboard can not answer it. If columns are added for resources requested, then the proposals we want (approved fro comp. cons.) are those proposals that do not request resources. This will be able to be answered pending #118.

**Comment by mbwatson** [comment]
@krobasky per #97 and #118, i have added a flag to indicate comp. cons. approval to the proposals table. please review to see if this question can now be answered.

**Comment by krobasky** [comment]
No, I cannot - That's going to be a question for Theresa. Put this in the 'feedback' column and ask at the next call.

**Comment by dcarsey** [comment]
Theresa - clarification between grant and funding :  grant submission vs. actual grant submission; funding - project when they will get funding; funding awarded; runs on cycles; October, February; June; Depending on date of submission, which cycle are they targeting for submission?  Target / projected date is inserted.  If they're still not ready, then they push back to the next submission cycle.  Usually at 6-9 months the proposal.  If you receive the Just in Time and pink sheets will give you an indication that they liked your proposal.

**Comment by rajshruti18** [comment]
Dates needed for this query:
1) Projected grant submission date
2) Actual grant submission date
3) Projected funding award date
4) Actual funding award date

**Comment by mbwatson** [comment]
@rajshruti18 I know _Projected grant submission date_ is  `"ProtocolTimelines_estimated"."plannedGrantSubmissionDate"` in the database and
_Actual grant submission date_ is `"ProtocolTimelines_estimated"."actualGrantSubmissionDate"` in the database.

We're already pulling in `"ProposalFunding"."fundingStart"`, but which date is that one -- _Projected_ or _Actual funding award date_, and where can I find the remaining date?

**Comment by mbwatson** [comment]
Location in database -> property of proposal on front-end

`"ProtocolTimelines_estimated"."estimatedStartDateOfFunding"` -> `estimatedFundingStartDate`
`"ProposalFunding"."fundingStart"` ->  `actualFundingStartDate`

**Comment by mbwatson** [comment]
waiting on hearing back about a possible mapping update per @rajshruti18

**Comment by rajshruti18** [comment]
@mbwatson updated the mapping, waiting on @xu-hao to update the pipeline

**Comment by rajshruti18** [comment]
@mbwatson Hao has updated the pipeline.

**Comment by mbwatson** [comment]
The four necessary dates are pulled in and rendered in the proposal tables. All that remains is to see if the question can now be answered.

**Comment by mbwatson** [comment]
@rajshruti18 and I think this can be answered. @krobasky , can you verify or suggest necessary additions?

**Comment by rajshruti18** [comment]
@krobasky Yes, this query can be answered. @mbwatson and I; both were able to successfully answer this one through ctmd-dashboard but we'll probably need to verify the accuracy of the results by showing it to Theresa and/or you.
