### ISSUE TITLE
Info from data WRT Oct 8 presentation

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#126]
Looped in Vanderbilt on the proposal and discussed the metrics on the proposals.  They want to do another meeting with only Vanderbilt.  Want to see how we’ve done things with the API.  
From flat to relational - they were surprised but excited.  It takes so many staff hours to pull the metrics, so they will be happy about this reduction in effort.
Terry (Michelle’s boss) -- Michelle is out on maternity leave; want their help in validating the numbers;

 Loading in the data - last minute help was needed.
Metrics data was not loaded in, talked about it without seeing it.
Dream WRT NIH (Director of TIN) Jane Atkinson:  pull down data from metrics and compare it against Human subjects data to confirm that teams are submitting everything and that our data is complete. 
Things that Jane Atkinson saw / was excited about:
Where info gets dropped in
How it populates studies as well as metrics
Everyone is responsible for loading their own info
How it broke out into each of the metrics - each site has their own metrics
Want to do a query (like all Duke as a site) across all of their metrics - Theresa mentioned this to Matt (site specific metrics)
Enrollment graph for HEAL studies

Profile data needs to be prettied up.   Currently very basic and in code speak.

**Comment by krobasky** [comment]
Data are loaded in now, and Duke doesn't require retraining.
