### ISSUE TITLE
Make more usernames (there will be 10 or less)

### ISSUE THREAD

**Issue by krobasky** [RENCI/ctmd#127]
Need log-ons to give full access to people at vanderbilt, johns hopkins, utah. Theresa will provide emails we can use for usernames, we will generate passwords and mail them.
We also need to ensure that a timestamp of when the users logged in and what pages were accessed is being logged.

**Comment by krobasky** [comment]
@mbwatson Dawn is getting the usernames from Theresa (#128), please see me about this if you have questions since it came up on the call while you were out.
Don't feel like you have to do the work, but if you can show somebody else how to create/modify the user accounts and monitor the logs, feel free to reassign

**Comment by mbwatson** [comment]
There are instructions for adding simple http auth users in the dashboard documentation: https://github.com/renci/dashboard#http-authentication, but I'm happy to handle this when I return.

**Comment by krobasky** [comment]
Whoa, nice documentation, @mbwatson !
OK, this is a high-prioritiy item (R1b) so if you're too bogged-down when the usernames come in from #128, please reassign this to me (and slack me a heads-up)

**Comment by krobasky** [comment]
•	Michelle Jones- michelle.i.jones@vumc.org
•	Meredith O’Brien- meredith.obrien@vumc.org
•	Julian Dunagan-julia.dunagan@vumc.org
•	Paul Harris- paul.a.harris@vumc.org
•	Terri Edwards- terri.edwards@vumc.org
from Theresa's 10/23 email

**Comment by mbwatson** [comment]
to be added to all-proposals _and_ HEAL-only dashboard

**Comment by mbwatson** [comment]
@mbwatson email passwords

**Comment by mbwatson** [comment]
theresa just got jhu
utah coming in soon

**Comment by dcarsey** [comment]
Nichol McBee = nmcbee@jhmi.edu
Ying Wang = ywang37@jhmi.edu

**Comment by dcarsey** [comment]
Marie Kay = Marie.Kay@hsc.utah.edu

Valeriya Vasenina =  Valeriya.Vasenina@hsc.utah.edu

I believe this is the end of the list of names for this special access group.

**Comment by mbwatson** [comment]
The credentials are added. Sharing the credentials is awaiting data, testing, and #135.
