### ISSUE TITLE
Get user names from Theresa

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#128]

**Comment by dcarsey** [comment]
Need up to 10 usernames from Theresa.
Hand off to Matt to generate user names and passwords.  If he's not the right person for it, he will re-assign it.
Get log-in and pw info back to Theresa. (Dawn / Matt)

**Comment by krobasky** [comment]
•	Michelle Jones- michelle.i.jones@vumc.org
•	Meredith O’Brien- meredith.obrien@vumc.org
•	Julian Dunagan-julia.dunagan@vumc.org
•	Paul Harris- paul.a.harris@vumc.org
•	Terri Edwards- terri.edwards@vumc.org
Added these to #127, too.
