### ISSUE TITLE
Profile data needs to be prettied up on site (so that labeling does not sound like "field names")

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#129]

**Comment by mbwatson** [comment]
@krobasky @dcarsey Please provide exact wording to use for each field, and I'll make the changes. Here are the field name replacements from my first stab at guessing what these should say:

- Proposal ID
- Network
- TIC
- RIC
- Type
- Has Linked Studies
- Design
- Study is Randomized
- Randomization Unit
- Randomization Feature
- Ascertainment
- Observations
- Pilot Study
- Phase
- Is Registry
- EHR Data Transfer
- EHR Data Transfer Option
- Study Requires Consent
- Is EFIC
- ORB Type
- Regulatory Classification
- ClinicalTrials.gov ID
- DSMB/DMC Required
- Number of Initial Participating Sites
- Enrollment Goal
- Initial Projects Enrollment Duration
- Lead PIs
- Awardee Site Acronym
- Primary Funding Type
- Funded Primarily by Infrastructure
- Source of Funding
- Date Funding was Awarded
- Was Previously Funded

**Comment by krobasky** [comment]
@mbwatson Good question - I think that list is good, regarding 'sounding like field names'. Theresa's comment on that may have been based on the old list, e.g., 'ProposalID' vs 'Proposal ID'.

Regarding 'prettied up' - maybe we can make it into a table so it doesn't take up so much whitespace? Let's apply changes like the following (on a guess) and then @mbwatson create a ticket for 'feedback' asking Theresa for specific edits with regards to ordering and 'info' that can be linked from each field to drill-down and explain what each field means. Can this serve as the 'data dictionary' for users desiring to upload the profile data?

|  Field           | Value  |  Field                                 | Value |  Field                                 | Value |
| ------------- | ------- | --------------------------- | ------ | --------------------------- | ------ |
| Proposal ID |             | Has Linked Studies          |           | Ascertainment                 |           |
| Network      |             | Design                             |           | Observations                   |           |
| TIC               |             | Study is Randomized      |           | Pilot Study                       |           |
| RIC               |             | Randomization Unit       |           | Phase                               |           |
| Type             |             | Randomization Feature  |           | Is Registry                       |           |

...etc.

**Comment by mbwatson** [comment]
Yeah, the dictionary thing makes sense to do. This is also a similar need to fulfill #10 .

I wonder if this information should be stored in the database, as it is application-specific. Otherwise we'd be customiizng/de-generalizing the front-end. There is a `name` table already in our database that we use to look up institution names and status names, which may be a good place to store these alternate names/descriptions. What do you think @xu-hao and @rajshruti18 ?

**Comment by mbwatson** [comment]
Per our conversation yesterday, I've added a dictionary lookup in the API to return display names and values back with query results. We just need to get the desired display names.

Next, I will begin to tidy up the profile interface.
