### ISSUE TITLE
Custom Report for Jane Atkins

### ISSUE THREAD

**Issue by mbwatson** [RENCI/ctmd#133]
We'll need a custom report of metrics for proposals approved for certain resources. The idea is that they want to know if providing resources makes studies perform better than, the same as, or worse than their non-resource-receiving counterparts. Moreover, this needs to be easy to generate -- as in, with a button.

This should be straight-forward, and will mostly come from REDCap piece.

**Comment by krobasky** [comment]
Jane Atkinson is the Director of TIN, let's prioritize this one.

**Comment by dcarsey** [comment]
Sankey diagram focused on this?
static Infographic -- some viz based on what they care about for metrics; actual numbers as well
WRT performance:
1) Is the proposal getting funded?
2) Is the site enrollment rate faster.  ex:  Target = 100.  How fast did you get them enrolled?  It matters HOW MANY were enrolled.  
3) What other metrics of performance should we look at?
Easy for her to run -- one button on front page - another card at bottom?  Generate a pdf functionality.

**Comment by davidborland** [comment]
Just commenting so I can participate

**Comment by davidborland** [comment]
Look at recruitment resources related to enrollment.

Different resources might have different outcomes of interest.

PDFs good

**Comment by davidborland** [comment]
Discussion with Theresa on 12/17/2019:
1. Might make sense to group IRB resources together
2. Enable clicking in bar chart to show proposals for that bar
3. Show proposals in a table
4. Could be useful to have funded/pending/not funded breakdown for requested/approved

**Comment by dcarsey** [comment]
From David on 1-24-2020 WRT progress on this task:

I think I completed everything I wanted to get done based on the initial feedback from Theresa. Going forward would really depend on more feedback from users (especially Jane Atkins).

So I don’t think there any remaining features to be completed, but there may be new features based on such feedback.
