### ISSUE TITLE
Update readme with git branching examples

### ISSUE THREAD

**Issue by krobasky** [RENCI/ctmd#137]
It might be nice to add an example of the git branching to the readme.

For example, in the dashboard [README.md](https://github.com/RENCI/dashboard/tree/bd0c751efe2387be9618347774c37639d06bc8ac), you might add the following under 'clone':

> Find and checkout the version you want to deploy. e.g.:
> `git branch -a`
> `git checkout 1.1.8`

@mbwatson if you agree with this update, feel free to assign the ticket back to me and I can make the change.

**Comment by mbwatson** [comment]
@krobasky Great idea. I'm happy to take this on.
