### ISSUE TITLE
rename 'dashboard' to 'ctmd-dashboard'

### ISSUE THREAD

**Issue by krobasky** [RENCI/ctmd#139]
All the ctmd repos that are not re-usable for other projects should be named with the 'ctmd' prefix. I'm not sure how disruptive or difficult this will be so I'm pushing it to phase 2.

**Comment by mbwatson** [comment]
I think we discussed this. I don't have permission to rename that repo.

**Comment by krobasky** [comment]
I just updated permissions on dashboard so that the whole txscience team has admin permissions - you should be able to rename it now.

**Comment by mbwatson** [comment]
@krobasky renamed!
