### ISSUE TITLE
Receive and upload data for the four HEAL proposals

### ISSUE THREAD

**Issue by krobasky** [RENCI/ctmd#142]
The heal-ctmd.renci.org server is up and running, ready for data. Data delivery ETA Nov 1 for Nov 15 deployment. W

**Comment by krobasky** [comment]
We also need to schedule time with Marcin and his delegate(s) for some sort of security audit:
 - [ ] upload data
 - [ ] initiate audit
 - [ ] triage any vulnerabilities
 - [ ] deploy (vet with team, announce to Theresa)

@mbwatson do we have doc yet for uploading data (SSD, ED)?

**Comment by krobasky** [comment]
@dcarsey Once the data are received, you can assign this ticket back to me, as I'd like to do the final acceptance testing upon uploading the HEAL data.

**Comment by dcarsey** [comment]
Still waiting.  Sent Theresa another nudge and told her it was blocking us.

**Comment by dcarsey** [comment]
sent requests on
11-1-19
11-5-19
11-11-19
11-14-19

**Comment by dcarsey** [comment]
Continuing to send requests for this 2 x a week.

We do have one proposal ID in hand:  #573 for PI = Jennifer Rabbitts, Tonya Palermno @ Seattle Children's Hospital

Effectiveness of an mHealth psychsocial intervention to prevent transition from acute to chronic postsurgical pain in adolescents
1UG3NS114858-01

**Comment by dcarsey** [comment]
The other HEAL studies are proposal numbers 590, 591, and 592.

Plus #573 as mentioned above.

**Comment by dcarsey** [comment]
Per 7/7/2020 Stakeholder meeting / Theresa:

HEAL studies to be submitted thru REDCap / TIN, but THAT IS THE END of TIN's involvement in HEAL studies.

All other data entry will be via HEAL-CTMD.

Data entry for HEAL site to include 

- milestones

- enrollment graphs

Canned reports would be nice (as a future feature).

Just as a reminder, HEAL studies do not get counted as a submitted proposal on CTMD.renci.org

**Comment by dcarsey** [comment]
Theresa's team will do this / test it out as they're uploading data.  If help is needed, Dawn will provide coaching.  They'll capture feedback for anything not working properly.

**Comment by dcarsey** [comment]
Stakeholder is successfully uploading data on HEAL.
