### ISSUE TITLE
Verify upload functionality on heal-ctmd

### ISSUE THREAD

**Issue by mbwatson** [RENCI/ctmd#144]

**Comment by krobasky** [comment]
Mock data (#148) would help a lot.
In the absence of mock data, ask @mbwatson or @dcarsey if they can provide the real data.

Use the CSV, not JSON, because that's what the user will ultimately want to provide for us.
@mbwatson can help with the formats.

**Comment by rajshruti18** [comment]
@mbwatson @dcarsey Can anyone of you provide me with the real data?

**Comment by mbwatson** [comment]
@rajshruti18 look for a message in slack at 12:32 today from me for the almost completely real data.

**Comment by rajshruti18** [comment]
Thanks @mbwatson!

**Comment by rajshruti18** [comment]
Successfully uploaded the files provided by Matt to heal-ctmd.

**Comment by krobasky** [comment]
@rajshruti18 did editting the data and uploading that also work?
...and what happens when you upload an empty file? Did it clear everything out? - that might be useful for 'sunset'-ing a server.
Can we also close #151, or are errors still not being reported?
You can 'close and comment' with your answers - thanks!

**Comment by rajshruti18** [comment]
@krobasky I was able to upload real data, mock data and blank csv file without any errors to heal-ctmd. No changes were reflected on the dashboard. We cannot close #151. Should I close this ticket?

**Comment by mbwatson** [comment]
it's configured to append data. i'll change it to replace table data, and that should fix this issue.

**Comment by mbwatson** [comment]
data replacement works. error checking remains, see #151

**Comment by mbwatson** [comment]
i believe @rajshruti18 already verified this. please confirm.

**Comment by rajshruti18** [comment]
@mbwatson Upload functionality works now.
