### ISSUE TITLE
Will RENCI store credentials of dashboard users?(QI)

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#154]
Waiting for an answer from ACIS.

ACIS assigned this to be ticket #2390.

**Comment by dcarsey** [comment]
From Marcin WRT storing credentials of dashboard users:  

It would be inappropriate for us to have their credentials. No one should have access to the human readable version of username and password pairs. 

In the meeting on Friday (Nov 15) we need to designate an application administrator. ACIS fills the role of system and infrastructure administration. We do not administer the application. It is the application admin that should document the configuration of the software and the admin level account credentials to manage the application.

**Comment by krobasky** [comment]
To close this ticket:
1. identify a "keeper" of the credentials and documentation of the qualified installation guidelines (let's call it a QI) - that can be @dcarsey 
2. identify an author of the QI (@mbwatson is qualified if he has time, or I can write it and he can edit it)
3. get confirmation that the "keeper" has the 'approved' QI

**Comment by krobasky** [comment]
related to #143, #157
