### ISSUE TITLE
change the main heal-ctmd and ctmd username and password

### ISSUE THREAD

**Issue by krobasky** [RENCI/ctmd#156]

**Comment by mbwatson** [comment]
this is not _in progress_ for me. relay to me the new credentials, and i'm happy to do this. should we put this in to do until it's actually in progress?

**Comment by krobasky** [comment]
To close this ticket, you or your delegate should:
1. generate a reasonably secure username (not 'duketic')
2. generate a password (using passwordgenerator or similar)
3. install the username/password on heal-ctmd
4. deliver the new username/password to Theresa (don't email 're: username/password' - send in separate emails and don't tag the password with 'password'
5. deliver the username/password to the team
6. delete duketic

**Comment by mbwatson** [comment]
gotcha. it was not clear that i was changing the credentials to to things of my choosing.

**Comment by mbwatson** [comment]
done. i will share at next meeting.
