### ISSUE TITLE
create plan of action for alert types sent to txscience@lists

### ISSUE THREAD

**Issue by krobasky** [RENCI/ctmd#158]
Figure out a place to publish 'what to do' when you get a nagios alert,
and also a schedule for who is 'on-call' for responding to the natios alert

One of the following partitions are full:
* /var 
* /opt

If the following isn't running:
* dockerd

If the following is inaccessible
* redcap

/backup

If something needs to be restarted

The following is above a limit for 4 consecutive tries in an hour:
* cpu
* memory
* http response time above 50ms

How many times people try to connect from same IP?

**Comment by dcarsey** [comment]
`[This Google Sheet has two tabs](https://docs.google.com/spreadsheets/d/1LAcWAGPJhDddgNKkZVAxH0U6P7B3p7Qg-sxcPFYfPXI/edit?usp=sharing)`

1) listing of problems that will trigger an alert PLUS the action to be taken

2) Placeholder for determining a schedule for who will be monitoring / timespan for the monitoring.

**Comment by dcarsey** [comment]
Alerts are being tested and steps to solve are being adjusted as need be.

**Comment by dcarsey** [comment]
Ask William at UNC if they can use the list of problems and solutions for monitoring the site that Kimberly developed.

[https://docs.google.com/spreadsheets/d/1LAcWAGPJhDddgNKkZVAxH0U6P7B3p7Qg-sxcPFYfPXI/edit?usp=sharing](url)

**Comment by dcarsey** [comment]
Sent to William on 1/24/2020.

**Comment by dcarsey** [comment]
Here is the final product -- [action plan for various alert types](https://docs.google.com/spreadsheets/d/1LAcWAGPJhDddgNKkZVAxH0U6P7B3p7Qg-sxcPFYfPXI/edit?usp=sharing)

**Comment by krobasky** [comment]
Done, action plan is here:
https://docs.google.com/spreadsheets/d/1LAcWAGPJhDddgNKkZVAxH0U6P7B3p7Qg-sxcPFYfPXI/edit
