### ISSUE TITLE
get Alex the list of software/libraries to scan for CVEs

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#167]
List for libraries:

all libraries are in the pipeline container:

apt-get:    
openjdk-8-jdk gnupu sbt python3-pip postgresql-client-11

pip: 
schedule pandas psycopg2-binary csvkit requests flask redis rq oslash sherlock

direct download: 
apache-spark

Front-end dependencies (NPM)

material-ui
nivo
axios
d3
d3-sankey
d3-scale-chromatic
d3-tip
material-table
react
react-dom
react-router-dom
react-scripts
webfontloader

API dependencies (NPM)

express
pg-promise
cors

Dockerd
yum-utils 
device-mapper-persistent-data 
lvm2
emacs
docker-ce
screen
traceroute

**Comment by dcarsey** [comment]
Sent on 12-6-19.

**Comment by dcarsey** [comment]
Sent on 12/6/2019

**Comment by dcarsey** [comment]
Now chasing down version numbers of libraries where appropriate.  Sent to Matt and Hao on 12/12/2019.

**Comment by mbwatson** [comment]
i think Alex is fine. do we still need to track this?

**Comment by dcarsey** [comment]
Only when/if we move forward with UNC CloudApps.
