### ISSUE TITLE
HTTP not working on heal-ctmd

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#169]
I submitted a ticket to ACIS to remind Marcin about this discovery:

The HTTP check simply isn't working, not a delay issue. I need to get to the bottom of it.

12-9-2019

**Comment by dcarsey** [comment]
Poked this on 12-13-2019

**Comment by mbwatson** [comment]
accidental close!

**Comment by dcarsey** [comment]
Response from Marcin 12-13-2019
I think you are referring to the http nagios check, to determine whether the site is up or down.
I have not yet been able to get the check to function correctly.
The lack of this nagios check should not stand in the way of launching. I would like to get it functional before then, but there are other checks in place that are monitoring the state of the system, such as the nagios check for the dockerd process.

**Comment by dcarsey** [comment]
Hi Kimberly,

I’ve created a ticket and will reach out to William about this.  I copied all of the email traffic on it onto the new ticket so that anyone technical will understand the thread.  (I understand it only on a very general level.)

Is it ok to close this ticket (#169) WRT checking with Marcin about it?

Thanks,
D

Yep!
