### ISSUE TITLE
Edit-in-place Study data wireframe

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#172]
Duke wants to use heal-ctmd.renci.org as the single source of truth for study and enrollment data. They will tell their PL's to edit the data in-place on the ctmd dashboard. We can request additional funding to get it done.

This is our most urgent task, so I'm marking it with 'bug' because they can't use the site to do the things they want without this feature. Please pull-in @luthfib to help wherever possible.

Close this ticket when:
 - You've drafted a design for a form allowing edit-in-place of Study data (instead of the CSV upload)
 - You've demonstrated and gathered feedback on your design to Dawn/Kimberly, and Duke if possible
 - Create new ticket(s) for implementing your design(s), accounting for full and increment back ups, locally and off-site (e.g., S3 bucket) 
 - Create ticket like this one for editing enrollment, and any other data in-place, per feedback.
 - Assign tickets to yourself, Hong, and Luthfi, ensuring they have the details required to implement it, and and add `1.52-staging` label to all the tickets.

Dawn's notes:
Filtering must work (including ED, SSD, profile uploads)

Duke team will give us a seperate ED, SSD, and profile uploads for heal and non heal. 

We need to figure out how to let them 'add' to existing uploads in the future, in addition to letting them replace everything. Designing that to be intuitive will be tricky

**Comment by krobasky** [comment]
I'm refining requirements with Duke now.

We need to be cognizant that 2 PLs may edit the same study, and if there's a collision, they might want to disgard PL1's edits, and keep the earlier, PL2's edits.

Here's one possible implementation:

* Users login from TIN so capture that username with each form submission by writing the form's input as a csv with pid, username, date-time in the filename; compress, then have those files copied over to S3 on daily cron
* provide list of those filenames from the data manager console, with option to restore that study's data from file

@mbwatson thoughts?

**Comment by dcarsey** [comment]
Dealing with a delete button - thoughts as of 1-5-2021 (Dawn to edit these after Jackie's feedback)
How will delete operate?  Need Jackie’s guidance.  Here are some of our thoughts:
to remove STUDY that is no longer funded:
Archive instead of delete button
MARK deleted instead of actual delete.
Toggle - to hide/show archived studies and a button to RESTORE (revive the archive)
Delete button will - NEVER delete the proposal #
Technical notes / reminders to ourselves:
Restore from 1 of several dates, counting back, option for only study profile data and enrollment data
Write it to a file when they click save.  Chron job goes thru 1x/wk and throws out things that are 12 mos old

**Comment by dcarsey** [comment]
Feedback from Jackie at 1-5-2021 meeting:

- Need tool tips for edit in place - STUDY PROFILE data (ticket #348  )
- REDCap items not editable (4)
- Study NAME to be added  ← don’t forget this on the editing field (ticket #348 )
- Confirmation question:  Are you sure you want to change data to proposal ID number and STUDY NAME
- Milestones ARE NOT editable - so do not include them on the edit in place fields.
- 

Jackie’s preference for how the RESTORE capability will work:

- Jackie wants it to RESTORE per study.  YES.  
- Create a record for each study to go back and select which parts of a bulk upload you want to edit.
- This could be an admin role:  site checks role / tier before allowing these buttons to be displayed
- A link lists what studies are affected by each upload
- Dialog box that in the interim, somebody saved a thing
- Puts lock in place after you upload a change
-

**Comment by luthfib** [comment]
Created tickets #354, #355, #356

**Comment by luthfib** [comment]
Created tickets #354, #355, #356
