### ISSUE TITLE
Confirm study profile fields w/ Theresa

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#179]
Confirm with Theresa that we have the right fields for the study profile.

Matt -- I think this is to make sure that our mock-up templates and mock data CSV are accurate.

**Comment by mbwatson** [comment]
the fields we need for the profile page are as follows, and i think these agree with the mock data CSVs.

- ProposalID
- network
- type
- linkedStudies
- design
- isRandomized
- randomizationUnit
- randomizationFeature
- ascertainment
- observations
- isPilot
- isRegistry
- ehrDataTransfer
- ehrDatatransferOption
- isConsentRequired
- isEfic
- irbType
- regulatoryClassification
- clinicalTrialsGovId
- isDsmbDmcRequired
- initialParticipatingSiteCount
- enrollmentGoal
- initialProjectedEnrollmentDuration
- leadPIs
- awardeeSiteAcronym
- primaryFundingType
- isFundedPrimarilyByInfrastructure
- isPreviouslyFunded

**Comment by dcarsey** [comment]
This list matches with the mock data csv.  Confirmed by Dawn.

**Comment by dcarsey** [comment]
Dawn to confirm with Theresa
