### ISSUE TITLE
How to handle potential REDCap vs. CSV overwrites for 4 fields (specified below)

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#183]
1. fundingSource
2. fundingAwardDate
3. proposalID
4. phase

- make a separate table that keeps them separate

- Pipeline checks table for data on those fields

- If there’s a discrepancy - we send an alert and let the user decide which info to use.

**Comment by mbwatson** [comment]
we'll use redcap as the source of truth for these fields, per meeting on 12/17/2019.

remove these fields, except id, from the csv upload template
