### ISSUE TITLE
Extend Sites Table in Database

### ISSUE THREAD

**Issue by mbwatson** [RENCI/ctmd#184]
I think we need to add a column `ctsaId` to the sites table, @xu-hao , to identify which CTSA to which a site belongs.

The sites data looks like this:

```csv
siteId,siteName,ctsaID
1,Arkansas Children's Hospital,30
2,St Christopher's Hospital for Children Drexel,0
3,Duke University Hospital,7
```

**Comment by mbwatson** [comment]
@rajshruti18 I think this may be more appropriately assigned to you.

**Comment by rajshruti18** [comment]
@mbwatson I think this issue can be closed. Please verify: [https://github.com/RENCI/HEAL-data-mapping/blob/master/CTMD%20data%20mapping_05192020.csv#L293]

**Comment by mbwatson** [comment]
when was this added because my db still only shows the two:

```bash
duketic=# select * from "Sites";
 siteId | siteName 
--------+----------
(0 rows)

duketic=# 
```

**Comment by rajshruti18** [comment]
@mbwatson It was added a while back, don't remember the exact date.

**Comment by mbwatson** [comment]
db on ctmd still shows only two columns:

```
duketic=# select * from "Sites";
 siteId | siteName 
--------+----------
(0 rows)
```

am i missing something?

**Comment by rajshruti18** [comment]
ctsa id exists in the mapping- [https://github.com/RENCI/HEAL-data-mapping/blob/master/CTMD%20data%20mapping_05192020.csv#L296](url)

**Comment by dcarsey** [comment]
@shruti will ask @xu-hao to update the database with CTSA ID for SITES CSV.  If i didn't say that quite right, somebody please edit this comment.  Thank you.  Dawn

**Comment by rajshruti18** [comment]
@dcarsey Sure! FYI The person you've tagged above is not me.

**Comment by dcarsey** [comment]
3rd column to be added in SITES template 
Site id  /  site name / ctsa ID / can have an additional column, but something that is easier to detect errors in is preferable (ex:  CTSA ID) / (they were considering using CTSA name, but that could inject so many errors)  <-- @mbwatson  says that if they really want CTSA name as a column, we can have an extra column for CTSA name that the pipeline will ignore.

**Comment by mbwatson** [comment]
duplicate of #221?

**Comment by mbwatson** [comment]
should appear when pipeline updates

**Comment by luthfib** [comment]
This ticket is done
