### ISSUE TITLE
Not all of the HEAL proposals are making it through from REDCap

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#194]
Proposals #590-592 are not coming through from REDCap
Please check pipeline.

**Comment by xu-hao** [comment]
They are in the database that the pipeline put the data into. The reason 590, 591 and 592 doesn't show up is because the proposal status is null, and in the query we use an inner join changing it to left join should fix that problem.

**Comment by krobasky** [comment]
@xu-hao thinks this works now, @mbwatson  has confirmed
