### ISSUE TITLE
Create a more beautiful figure of SSO plan

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#207]
Use Kimberly's white-board drawing.
Make it beautiful for Matt's D3 SSO plan document deliverable.

**Comment by krobasky** [comment]
Is this a "must-have" or a "nice-to-have", and should we re-triage to FY 2022, accordingly?

**Comment by dcarsey** [comment]
Discussion on 7-16-2020 -- table for later.  Possible work for a student.

**Comment by dcarsey** [comment]
Deliverable has been completed.  This is no longer needed.
