### ISSUE TITLE
After Shruti updates TIC RIC Assign - check w/ Matt

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#220]
Make sure that Matt is aware the mapping was done and remind him of the following:

Only meeting date 2 is needed; 
TIC RIC assign we will need both items captured (initial assignment + assignment after vote)

**Comment by mbwatson** [comment]
i was under the impression that the pipeline will take care of this and nothing needs to be changed on the front-end. is this not the case?

**Comment by rajshruti18** [comment]
> 
> 
> i was under the impression that the pipeline will take care of this and nothing needs to be changed on the front-end. is this not the case?

@mbwatson Yes, you are right. You won't need to change anything on the front-end for this field.

**Comment by rajshruti18** [comment]
Done!
