### ISSUE TITLE
Add CTSAID field to SITES table of database in order to connect sites to their CTSAs

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#221]
We need to extend SITES table in database by adding a ctsaId field in the SITES table of the database to connect sites to their CTSAs

**Comment by dcarsey** [comment]
Hey Shruti.  We've re-assigned this task to you.  THANKS.  Dawn

**Comment by rajshruti18** [comment]
@mbwatson I'm not sure about this one. Is this done?

**Comment by rajshruti18** [comment]
This is done [https://github.com/RENCI/HEAL-data-mapping/blob/master/CTMD%20data%20mapping_05192020.csv#L293](url)
