### ISSUE TITLE
Performance tuning of Pipeline

### ISSUE THREAD

**Issue by xu-hao** [RENCI/ctmd#228]
Currently, the pipeline is slow because it has a start-up time.
Can it be faster if it has a separate Spark process running in background waiting for job requests instead of restarting Spark process every time we run the pipeline.

**Comment by xu-hao** [comment]
This is not the limiting factor right now.

**Comment by luthfib** [comment]
Duplicate of https://github.com/RENCI/ctmd/issues/329
