### ISSUE TITLE
reorganize dashboard repo to reflect dependencies

### ISSUE THREAD

**Issue by krobasky** [RENCI/ctmd#23]
ticpmd repo should have dashboard under it, and dashboard should have sub-repos as depencies

**Comment by krobasky** [comment]
be sure all the repo pointers are current

**Comment by xu-hao** [comment]
ctmd submodule references are update to date

**Comment by xu-hao** [comment]
tag release r1b

**Comment by xu-hao** [comment]
the pointers need to be updated every time we have a new release of a component

**Comment by mbwatson** [comment]
i think this is done
