### ISSUE TITLE
Monitoring ACIS ticket:  request to tear down stage-pmd.renci.org VM

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#235]
Requested to help@renci.org:

Please tear down stage-pmd.renci.org VM, it’s no longer needed.

Can you please spin up dev-ctmd.renci.org, mirroring the exact same configuration as stage-ctmd.renci.org? A copy of the image would be perfect, if that’s possible, otherwise we can re-install the software.

**Comment by dcarsey** [comment]
@krobasky  -- This was a help ticket you submitted to ACIS on 6-5-2020.  Have they responded?  I was trying to track it.

**Comment by dcarsey** [comment]
Update:
Yes, ACIS did their part. We asked rciadmni to do this to fulfill request from Vandy to implement https on stage-ctmd. Check with Matt to be sure everything now works for https on both ctmd and stage-ctmd, to my knowledge it is working.

but ctmd still should be deployed on dev-ctmd.renci.org. Ask Matt if he's going to do that; you may need to create a ticket for him?

**Comment by krobasky** [comment]
The certs are now there, I think stage-pmd is torn down - maybe ask Matt to confirm?
dev-ctmd.edc.renci.org is there, but I can't access it. @mbwatson can you access?
