### ISSUE TITLE
How statuses are lumped into the OTHER category

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#236]
We group a bunch of statuses together into four named groups per Michelle, and the remaining are lumped into "other" in the new CTMD graphic. These are the statuses that are lumped into the "other" category.

 Approved for Network Support
 N/A: HEAL Study
 No Further Network Support
 No Longer Providing Resources
 Not Approved
 On Hold
 Pending Re-submission
 Pending Submission
 Re-Submitted
 Ready for NCATS Review
 Returned to Investigator
 Submitted
 Under Review
 Withdrawn by PI
 Withdrawn by PI post-award

**Comment by krobasky** [comment]
Is this really 'documentation'? I thought there was dev to be done here, too...
