### ISSUE TITLE
Tooltips on Proposal Table Column Headers

### ISSUE THREAD

**Issue by mbwatson** [RENCI/ctmd#238]
fields and proposals table columns are getting unruly. having tooltips to describe these columns would be helpful.

**Comment by mbwatson** [comment]
ok, now we'll just need to know what the more informative tooltips should say. i've got tooltips that basically the same thing as the column header text right now:
![Screenshot from 2020-07-14 14-33-43](https://user-images.githubusercontent.com/6019870/87463379-49842f80-c5df-11ea-80eb-fc5ea51f1a5d.png)

**Comment by dcarsey** [comment]
[https://drive.google.com/file/d/17SK3FveDYbVKFdZahATbuj4JekOMnj4r/view?usp=sharing](url)

^^ Here are Jackie's suggestions for Tool Tips descriptors.  

However, I am following up on some of the comments that she made.  So don't start on this task yet, unless you want to do it twice.

**Comment by rajshruti18** [comment]
> [https://drive.google.com/file/d/17SK3FveDYbVKFdZahATbuj4JekOMnj4r/view?usp=sharing](url)
> 
> Note: they're on tab labeled COLUMN HEADER AND COMMENTS
> 
> ^^ Here are Jackie's suggestions for Tool Tips descriptors.
> 
> However, I am following up on some of the comments that she made. So don't start on this task yet, unless you want to do it twice.

@dcarsey I plan on working on this issue and wanted to have a look at Jackie's suggestions but the link seems to be broken.

**Comment by dcarsey** [comment]
[https://drive.google.com/file/d/17SK3FveDYbVKFdZahATbuj4JekOMnj4r/view?usp=sharing]

Please note tab 2 and the words in parentheses in the top row.

**Comment by rajshruti18** [comment]
Merged PR- https://github.com/RENCI/ctmd-dashboard/pull/157. Need feedback from Jackie.
