### ISSUE TITLE
URGENT: D1 TIN Dashboard / CTMD “single sign-on” (SSO) by 9-30-2020

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#243]
Target delivery Calendar Year 2020/Q3

Close this ticket when:
1. Matt and Kyle have demonstrated a REAL single-sign-on between TIN Dashboard and CTMD with Kyle, using the code that we will use in perpetuity for this feature.
2. Dawn (acceptance tester) has been notified of the test, witnessed and verified that SSO works

@mbwatson please make tickets from sub-tasks as needed, feel free to assign people to those tasks if these are things you need help with, but also be sure to add the tickets to 'triage please' column and slack to #tic telling Dawn and I the tickets are there and need triaging.
If you do make sub-tasks that are necessary for this deliverable, please tag those new tickets with #243 and move this ticket back into the deliverable column to show it is entirely comprised of those sub-tasks.

**Comment by dcarsey** [comment]
Matt's thoughts WRT roadmap for SSO

[https://docs.google.com/spreadsheets/d/1ZqPozNrIYuhyJVKK3xo1WMHQu-XQ3NkZPdOMfzu2rvs/edit?usp=sharing]

**Comment by krobasky** [comment]
Repo for implementation:
https://github.com/RENCI/tx-autht

**Comment by dcarsey** [comment]
1) Put code in repo (will reuse it for cellfie).
2) Hong MIGHT be available to help w/ this SSO issue.
3) Matt creating something locally first.
