### ISSUE TITLE
ADDITION to Proposals by application status visualization

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#251]
CTMD home page - Proposals by Application Status:  TIC/RIC unassigned
Can we make a new bar graph in that section that makes the math add up?
The number assigned to EACH TIC/RIC + "unassigned" = total # of proposals at top of page.

Here are the categories for the last bar graph:
Needs to be assigned (because it is a new submission)
Returned to investigator
Withdrawn by PI
Not approved - no longer in the workflow (everybody gets an initial consult now) (4 permanently at this old workflow/status) - will still need it listed in order to add up to the magical # at the top

Note to self:
Browse by TIC/RIC  - "unassigned" to be added to the donut
Separate bar next to the others - broken down by category

**Comment by mbwatson** [comment]
these changes are live in production.

![Screenshot from 2020-07-09 11-42-25](https://user-images.githubusercontent.com/6019870/87061105-5537b680-c1d9-11ea-89b4-31b077cd93b5.png)

![Screenshot from 2020-07-09 11-42-47](https://user-images.githubusercontent.com/6019870/87061112-579a1080-c1d9-11ea-94de-c7df7d7846a7.png)
