### ISSUE TITLE
Add blocklist functionality

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#258]
Add blocklist functionality to CTMD
(similar to the safelist/whitelist feature)
EXCEPT that it lists proposal IDs in a file that should be BLOCKED from CTMD

Add a list of what we think are the 'test' proposals
In a separate file, duplicate the list of HEAL proposal IDs we are using as the SAFELIST on heal.ctmd.renci.org

Code maybe goes here:
https://github.com/RENCI/map-pipeline/blob/master/src/main/scala/tic/Transform2.scala#L48

**Comment by mbwatson** [comment]
FY/MI, these are HEAL studies

```bash
duketic=# select "ProposalID" from "Proposal" where "Proposal"."ShortTitle" like 'HEAL:%';
 ProposalID 
------------
        573
        590
        592
        591
(4 rows)
```

**Comment by mbwatson** [comment]
redeployed yesterday evening to stage-ctmd. HEAL proposals still make it into the database, so we're investigating a possible bug.

**Comment by xu-hao** [comment]
this is done
