### ISSUE TITLE
0.5 Proposals in Resource Metrics graphic

### ISSUE THREAD

**Issue by mbwatson** [RENCI/ctmd#271]
the tooltip in the Resource Metrics graphic on heal-ctmd, shows "0.5 proposals":
![Screenshot from 2020-07-23 10-00-59](https://user-images.githubusercontent.com/6019870/88295637-af517500-cccb-11ea-946e-10032ccb78b6.png)

I haven't looked into this yet.

**Comment by dcarsey** [comment]
Sister ticket to #300

**Comment by davidborland** [comment]
Just pushed a fix for this.
