### ISSUE TITLE
Add COVID research as a field to CTMD

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#272]
Watch for added field info (via Google form / change management) WRT COVID research.  

There is a new question on the proposal intake form:
Is this submission related to COVID research?

We'll need to incorporate that into the CTMD.

To close this ticket:
1. add a column in the data map
2. make sure there is a test for it 
3. reassign this to Matt to get this on the dashboard and move to 'triage please'
4. add to the dashboard in the proposal table  (Matt will do)

**Comment by rajshruti18** [comment]
Added the COVID field to the mapping and passed on the information to Hao to update the pipeline and asked him to let Matt know the same so that he can re-sync the dashboard.
