### ISSUE TITLE
Map test dataset to redcap fields (reverse)

### ISSUE THREAD

**Issue by krobasky** [RENCI/ctmd#279]

**Comment by krobasky** [comment]
Look into ryan's test data repo and see what you can do to operatinoalize that data on the dev-ctmd.renci.org site.

**Comment by krobasky** [comment]
test data repo is here: https://github.com/RENCI/ctmd-test

**Comment by krobasky** [comment]
add Luthfi when he comes on board.

**Comment by krobasky** [comment]
#262

**Comment by krobasky** [comment]
Ryan's synthetic data are here: https://github.com/RENCI/HEAL-data-mapping/blob/master/goldenData.json
But these don't map to the redcap NVP structure, they instead map to our internal data model.
Consequently, we can't use these data to test all the paths through all the code.
So the job is to create a new synthetic dataset that truly mimics the redcap data insofars it can replace the redcap data feed at the point the data are first ingested by the CTMD.

The new dataset is not required to contain the same content, and it can be very small and simple, but part of the job will be to test that the ingest works on the new dataset.

That means coordinating with Luthfi, Hong, Matt and Kimberly to find out where the data is ingested in the pipeline.

**Comment by rajshruti18** [comment]
Done. See https://github.com/RENCI/ctmd/issues/434
