### ISSUE TITLE
Make the Collaborations tab on CTMD respond faster

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#284]
David, our best thinking on this so far led us to this point:

Turn on only 2 or 3 of the node types by default

Add a couple of labels to indicate that the dropdowns are for highlighting and the legend controls which node types are shown

If that doesn't do the trick, then we could try the separate tabs, probably in conjunction with 1 and 2.

**Comment by dcarsey** [comment]
David -- I discussed this with Theresa, and she confirmed that this is a great idea - to make it so that the page loads faster and that it is a little easier to understand.

ALSO, anything we can do to make the page not so overwhelming would be good, and to make it clear to the user that additional categories (fields) can be added to the visualization.  

FWIW, she said that the NCATS leaders in particular found this page very helpful.

**Comment by dcarsey** [comment]
Collaborations tab -- 

- use TIC/RIC in labeling the node / category at the top.

- Instead of using the word NODE in the instructions on the screen, use the word **category**.

- I'll get you the two categories (nodes) that should be defaulted.

- Reminder to punch up the instructions w/ a box or bold print or something.

- change the header "organization" to CTSA/Organization

**Comment by davidborland** [comment]
A thought: is "Collaborations" the best name for this page? Seems like its really more of a means to explore relationships between different proposal categorizations/features.

**Comment by dcarsey** [comment]
I think they are interested in splitting network and Sankey into 2 different pages.

Make nodes larger so that it's easier to click on them (more separation)

Dawn would like a little more training on the various features of these diagrams, including how to work the Proposals table below it.

**Comment by dcarsey** [comment]
@davidborland  First of all, that graphic is killer and it is very responsive now.  Thanks so much for your work on it and the additional features you've added.  

We now have the 2 categories that they'd like to see as the defaults:  **TIC/RIC and CTSA**.  They decided that the other graphics feature other things, so it might be nice for this Collaborations tab to at least initially demonstrate CTSA activity.

**Comment by davidborland** [comment]
Implemented. Should be available after Matt merges and deploys.
