### ISSUE TITLE
REMOVE new_funding_source field and replace w/ NEW FUNDING STATUS

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#290]
New Funding Source (header in proposals table) field maps to 'new_funding_source' field in the REDCap database. I think we should remove this field from the dashboard and instead include a 'New Funding Status' field which maps to both updated_funding_status & new_funding_source-- it would be better. 

Other places to update:  remove new funding source from mapping;   will this touch anything else?  Think on this.

**Comment by rajshruti18** [comment]
The mapping is already in place, this change needs to be made by Matt on the front-end.
