### ISSUE TITLE
Pulling in correct data to Approved Resources graphic

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#300]
Email chain spelling out correct fields needed to correct this issue:
[Approved Resources graphic mapping corrections.pdf](https://github.com/RENCI/ctmd/files/5170729/Approved.Resources.graphic.mapping.corrections.pdf)

The fields needed are: 
servicesPatOutcome + 
servicesPostOutcome - 
removedServices

**Comment by rajshruti18** [comment]
Below are the numbers that I got:
**RAW DATA:**
Operationalize Standard Agreements-15
Operationalize Single IRB-64
Recruitment Feasibility Assessment-4
Recruitment Plan-26
Recruitment Materials-34
Community Engagement Studio-15
EHR-Based Cohort Assessment-21
Innovations & Clinical Effectiveness Trial Design-2
Other-0
**STAGE-CTMD:**
Operationalize Standard Agreements-14
Operationalize Single IRB-0.5
Recruitment Feasibility Assessment-3
Recruitment Plan-25
Recruitment Materials-33
Community Engagement Studio-14
EHR-Based Cohort Assessment-20
Innovations & Clinical Effectiveness Trial Design-1
Other-3
The numbers do not match.

**Comment by dcarsey** [comment]
Dumping info from Ticket #303 to combine these into ONE ticket:

Similar to the problems with APPROVED RESOURCES, the REQUESTED RESOURCES need to be checked for the data being pulled into the graphic.
Some of the categories listed in the Requested/Approved Resources graphic are resources that have been renamed over time.

Do we need to condense these into streamlined categories so that there aren't so many holes on the graphic?

We also need to figure out why SIRB is not coming into the graphic, because it is accurate in the CTMD data base.

David says : the graphic is set up to populate from data in the requestedServices and approved Services arrays for each proposal. Are we able to match that up w/ the algorithm / pipeline / info in the database ?

FWIW, we are also not pulling in OTHER and OTHER RESOURCES in the graphic, and we need to confirm if the numbers we do have for it are accurate.

**Comment by dcarsey** [comment]
From 9-22-2020 meeting w/ Michelle and Jackie (regular Tuesday meeting)

Michelle indicated that the field names were already reconciled in the TIN (ex: when the SIRB resources were renamed from Operationalize Central IRB to Single IRB).

Michelle suggested we look at our old notes about mapping / 1 for 1 matching that was done w/ field names.  I looked briefly at 
Shruti's mapping document:  https://docs.google.com/spreadsheets/d/1qpaXdxZLYobfCudaD_z6U156FPgEA6gO/edit#gid=1922452661

I think the following lines / fields will lead us closer to an answer.  Please think on these and see if it is a reasonable starting point for untangling things.

line 94: CIRBfwaNumber = fwa
line 126: CIRBrecommendation = recommendations1
line 127: SArecommendation = recommendations2   (SA = standard agreements)
lines 96-105 or 106
line 123 ? also includes the word recommendation, but there's a typo in our column for the field name
line 124 ? has the word recommendation in it
line 135 ? has the word recommendation in it
Note comment on line 137

**Comment by dcarsey** [comment]
Notes from internal meeting / solutions
Mapping for Requested Resources vs. Approved Resources - updates from Shruti
How can we resolve this issue?
Dropdown options are slightly different for a few of the fields
Michelle - reconcile the fields on the front end?
Slightly different names for the resources
Study planning - ask Jackie if it needs to display on the graphic (since everybody gets it if they request it)
Matt needs an API where the data needs to be aggregated or removed on the back end
New component to add this facility - feature
Can’t just do it at the mapping level
Can we do it on the actual SQL /query end ?
Find the dropdown options
Queries are in the API controllers
Point KR at the code, she can right the SQL for it
https://github.com/RENCI/ctmd-dashboard/blob/404ecdabffe054b8a678dbe3e2a05f8a077c21cc/api/controllers/proposals.js#L256
^^ returns the proposals array, references a get proposals promise (right above it in the file), uses a query called proposals query (which is a few chunks of code above that)
Line 212 is get proposals promise
Library interacts w/ postgres; runs a task and keeps same db open but runs several queries for you
Line 212 tasks, takes proposals, grabs profiles, grabs srvcs, loops over and matches everything up
Below the proposals query a few lines down …. Might be where the transformation will happen

**Comment by mbwatson** [comment]
sorry--we also need this resources query to match: https://github.com/RENCI/ctmd-dashboard/blob/0a058c24f99596117a9edcd8b9cda6656491d7e5/api/controllers/resources.js#L3

the response look like this: https://ctmd.renci.org/api/resources

["Single IRB","Operationalize Standard Agreements","Study Planning (Design, Budget, Timelines, Feasibility)","Standard Agreements","Operationalize Central IRB","Recruitment Feasibility Assessment","Recruitment & Retention Plan","Recruitment Plan","Recruitment Materials","Community Engagement Studio","Other","EHR-Based Cohort Assessment","Innovations & Clinical Effectiveness Trial Design"]

**Comment by krobasky** [comment]
Please add the github hash(es) for the commit(s) used to close this ticket. It'd be great to tag the commit with this ticket, too (e.g., #300)

To close this ticket:

1. Make sure this graphic properly collapses the different columns
2. Ask Dawn or Kimberly to confirm

![image](https://user-images.githubusercontent.com/413166/98257825-22ff5100-1f4e-11eb-9010-2ef5e2ebcb6c.png)

**Comment by krobasky** [comment]
For the pink column, to rename, the API outputs will be updated too, with the query changes:
https://stage-ctmd.renci.org/api/resources/approved

**Comment by rajshruti18** [comment]
all resources: https://ctmd.renci.org/api/resources

approved resources: https://ctmd.renci.org/api/resources/approved

requestsed resources: https://ctmd.renci.org/api/resources/requested

**Comment by rajshruti18** [comment]
> sorry--we also need this resources query to be updated: https://github.com/RENCI/ctmd-dashboard/blob/0a058c24f99596117a9edcd8b9cda6656491d7e5/api/controllers/resources.js#L3
> 
> the response look like this: https://ctmd.renci.org/api/resources
> 
> ```
> [
>   "Single IRB",
>   "Operationalize Standard Agreements",
>   "Study Planning (Design, Budget, Timelines, Feasibility)","Standard Agreements",
>   "Operationalize Central IRB",
>   "Recruitment Feasibility Assessment",
>   "Recruitment & Retention Plan",
>   "Recruitment Plan",
>   "Recruitment Materials",
>   "Community Engagement Studio",
>   "Other",
>   "EHR-Based Cohort Assessment",
>   "Innovations & Clinical Effectiveness Trial Design"
> ]
> ```

To resolve this issue please review- https://github.com/RENCI/ctmd-dashboard/pull/137

**Comment by mbwatson** [comment]
here's what the graphic shows with the updated resources queries from 

![Screenshot from 2020-11-05 15-51-43](https://user-images.githubusercontent.com/6019870/98295032-e1d36500-1f7e-11eb-9618-fca1f81b7cc7.png)

further investigation will be needed probably to see why the grouping isn't happening. i will be able to look into this further today or tomorrow, but perhaps @davidborland has insight as he wrote this piece.

**Comment by mbwatson** [comment]
silly mistake on my part--there was another reference to the new `service2` column elsewhere in the proposals controller that needed updating. looks good now!

![Screenshot from 2020-11-05 17-09-53](https://user-images.githubusercontent.com/6019870/98302140-e5201e00-1f89-11eb-93bc-4f43ca18b8c0.png)

@dcarsey do the numbers look right?

**Comment by mbwatson** [comment]
still more work to do here. it looks like the names and their replacements are backward. the resources (seen by hitting https://stage-ctmd.renci.org/api/resources/) are:

```
[
  "Single IRB",
  "Study Planning (Design, Budget, Timelines, Feasibility)",
  "Standard Agreements",
  "Recruitment Feasibility Assessment",
  "Recruitment & Retention Plan",
  "Recruitment Materials",
  "Community Engagement Studio",
  "Other",
  "EHR-Based Cohort Assessment",
  "Innovations & Clinical Effectiveness Trial Design"
]
```

these are results from the query [here](https://github.com/RENCI/ctmd-dashboard/blob/240b59c2c054c8ce2ff0578e7966a8a47b034397/api/controllers/resources.js#L4).

i think, then, that this needs to be tweaked to match the resource-renaming in the proposals query [here](https://github.com/RENCI/ctmd-dashboard/blob/240b59c2c054c8ce2ff0578e7966a8a47b034397/api/controllers/proposals.js#L205), as seen in the image below.

![Screenshot from 2020-11-06 10-48-41](https://user-images.githubusercontent.com/6019870/98386080-c4090d00-201d-11eb-9710-24706127bc70.png)

**Comment by rajshruti18** [comment]
> still more work to do here. it looks like the names and their replacements are backward. the resources (seen by hitting https://stage-ctmd.renci.org/api/resources/) are:
> 
> ```
> [
>   "Single IRB",
>   "Study Planning (Design, Budget, Timelines, Feasibility)",
>   "Standard Agreements",
>   "Recruitment Feasibility Assessment",
>   "Recruitment & Retention Plan",
>   "Recruitment Materials",
>   "Community Engagement Studio",
>   "Other",
>   "EHR-Based Cohort Assessment",
>   "Innovations & Clinical Effectiveness Trial Design"
> ]
> ```
> 
> these are results from the query [here](https://github.com/RENCI/ctmd-dashboard/blob/240b59c2c054c8ce2ff0578e7966a8a47b034397/api/controllers/resources.js#L4).
> 
> i think, then, that this needs to be tweaked to match the resource-renaming in the proposals query [here](https://github.com/RENCI/ctmd-dashboard/blob/240b59c2c054c8ce2ff0578e7966a8a47b034397/api/controllers/proposals.js#L205), the results from which are illustrated in the image below.
> 
> ![Screenshot from 2020-11-06 10-48-41](https://user-images.githubusercontent.com/6019870/98386080-c4090d00-201d-11eb-9710-24706127bc70.png)

Tweaked the query in resources.js--- https://github.com/RENCI/ctmd-dashboard/blob/f035974e610262dfcf2ee1def3d27f22a59215de/api/controllers/resources.js#L4

**Comment by mbwatson** [comment]
thanks @rajshruti18 for fixing the resources query. now https://stage-ctmd.renci.org/api/resources/ returns

```
[
  "Operationalize Single IRB",
  "Study Planning (Design, Budget, Timelines, Feasibility)",
  "Operationalize Standard Agreements",
  "Recruitment Feasibility Assessment",
  "Recruitment Plan",
  "Recruitment Materials",
  "Community Engagement Studio",
  "Other",
  "EHR-Based Cohort Assessment",
  "Innovations & Clinical Effectiveness Trial Design"
]
```
which matches the resources returned with proposals (see example in the image above).

so NOW the graphic looks like this

![Screenshot from 2020-11-06 11-28-09](https://user-images.githubusercontent.com/6019870/98391173-4b597f00-2024-11eb-9bf8-f0599469b9a3.png)

what do you think about this @dcarsey ?

**Comment by dcarsey** [comment]
Feedback from Jackie:
Change labeling from REQUESTED RESOURCES to REQUESTED SUPPORT
2nd line will remain APPROVED RESOURCES
Study planning is not truly a resource, so please move it to the far right  column so that it doesn't throw off the alignment
Don't include study planning on bottom row.
Not everything will have a matching one underneath.
Headers don't line up and are chopped off
Headers on the bottom would be helpful

Let Dawn know when these formatting changes have been made ^^^ so she can confirm with Jackie and revisit this question:
TBD:  Should comprehensive consultations be added?
