### ISSUE TITLE
Verify data being pulled for REQUESTED RESOURCES graphic

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#303]
Similar to the problems with APPROVED RESOURCES, the REQUESTED RESOURCES need to be checked for the data being pulled into the graphic.

Jackie is coming up with slightly different numbers and not sure why
looking at the proposal submission form to find this and excluding consults that do not have a submission date. 
not sure if missing other logic.

**Comment by rajshruti18** [comment]
Below are the numbers that I got:
**RAW DATA:**
Operationalize Standard Agreements-15
Operationalize Single IRB-64
Recruitment Feasibility Assessment-4
Recruitment Plan-26
Recruitment Materials-34
Community Engagement Studio-15
EHR-Based Cohort Assessment-21
Innovations & Clinical Effectiveness Trial Design-2
Other-0

**STAGE-CTMD:**
Operationalize Standard Agreements-14
Operationalize Single IRB-0.5
Recruitment Feasibility Assessment-3
Recruitment Plan-25
Recruitment Materials-33
Community Engagement Studio-14
EHR-Based Cohort Assessment-20
Innovations & Clinical Effectiveness Trial Design-1
Other-3

The numbers do not match.

**Comment by dcarsey** [comment]
Some of the categories listed in the Requested/Approved Resources graphic are resources that have been renamed over time.  

Do we need to condense these into streamlined categories so that there aren't so many holes on the graphic?

We also need to figure out why SIRB is not coming into the graphic, because it is accurate in the CTMD data base.

David says :  the graphic is set up to populate from data in the requestedServices and approved Services arrays for each proposal.  Are we able to match that up w/ the algorithm / pipeline / info in the database ?

**Comment by dcarsey** [comment]
The information in this ticket has been added to Ticket #300 and closing this ticket now.
