### ISSUE TITLE
CSV uploads not working

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#319]
(check both CTMD and HEAL to make sure uploads are working properly.)

If the csv upload isn’t working, or if the disks are full, it might be because the volumes aren’t getting deleted. Always delete the volumes using -V with docker-compose
To see what is the name of attached volumes:
can do a docker inspect <redis container> on the redis container and then use docker volume prune <volumes>
also add that used docker ps to look for the redis containers

More history on this topic:

Things we learned in the process:

Temporary directory found that needed to be deleted
Redis data directory was deleted
It’s on the host that’s mounted to the container
Beta? Under redis directory
Why was it blocking us from uploading CSV files?
Redis queue uses redis to keep track of tasks that are running
If you stop running / forcekill the redis container, the redis would still have the status of some tasks as being running
When you restart it it will think it wants to finish, and it won’t start a new task
Container was force deleted maybe months ago
If it happens again, it could go unnoticed for weeks if we ever had to restart it
Do we need a nagios alert for this?
Procedures for restart?
We changed the docker container so that we mounted a new directory so that it won’t be a problem (volume?)
Reassign it to Kimberly to see if she needs to flesh out the instructions
Remade the directory and it worked fine
Be careful about deleting volumes
Need to rebuild and re-sync the database after these changes were made
Need to tell Duke the site may be down while we re-sync

Functionality of CTMD = read-only dashboard
•	If I choose a file to upload, it wipes out everything that’s there previously.
•	Remind Duke BEFORE we have to upload / possibly obliterate data – ASK THEM for the spreadsheet / data so that we can upload it when we’re done.

**Comment by xu-hao** [comment]
What happens when user uploads CSV?

**Comment by mbwatson** [comment]
updates from dawn:

STAGE - SITES tab:  I was able to upload data BUT it did not write over existing data.  See SITES tab in Stage to check for duplicate site numbers.  (Reminding us:  on CTMD, Jackie couldn't upload anything to SITES, but I could. Also, it didn't WRITE OVER the existing data.)

STAGE - CTSA tab:  behaved exactly the same way it did on CTMD:  CTSA CSV upload: I exported the existing data SO I WOULDN"T LOSE IT THIS TIME and added 3 fake fields to it. it tells me file selected, but can't get it to upload, even when I try doing a hard refresh.

STAGE - STUDIES tab:  behaved exactly the same way it did on CTMD:   I tried to upload REAL DATA that I captured from it last week PLUS ONE FAKE study. It acted like I had correctly SELECTED and UPLOADED the file, but no amount of hard refreshing would bring it into view.

**Comment by mbwatson** [comment]
uploads were working fine. turns out i wrote a bad promise in the api :(

this is fixed in 1.40-staging, which is deployed currently on dev-ctmd and stage-ctmd

**Comment by dcarsey** [comment]
Current status report:

- CSV template for SITES needs a 3rd column (CTSA ID)
         - Site id  /  site name / ctsa NAME (both site and ctsa names need to be max area)
         - Make sure that info is in the data base
         - Hao has completed this step
         - Matt will redeploy and those changes will come through
- we need a CSV template for uploading enrollment data 
- and to make sure the mapping / data base work has been done behind the scenes so it lands in the right spots
            - The template exists, but is not on the site yet.
            - Data is mapped and connected in the data base
            - It’s all ready to be moved over.  
- Double-check mapping and fields
- Making sure that the uploads function as read-only and writes over existing data
**Jackie is re-thinking and checking w/ Theresa WRT how this operates for STUDY PROFILE uploads.**
**Reminder (Dawn):  Make sure that Jackie knows the CTSA template was replaced on Wednesday.**

**Comment by dcarsey** [comment]
Success after Jackie changed font sizes to match CSV and unclicked right-justify.
Waiting for Jackie's problematic files to examine / replicate error.

**Comment by dcarsey** [comment]
Currently, enrollment data is the only upload that MAY NOT be working.   Dawn to confirm with Jackie if it is user error.

**Comment by dcarsey** [comment]
The upload mechanism IS working.  Other issues surrounding templates and possibly user error are embraced in tickets #346 and #341.
