### ISSUE TITLE
CSV uploads can be XL upload instead

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#325]
Expand options for CSV uploads to CTMD to include .xlsx instead of just CSV

**Comment by mbwatson** [comment]
is this still something we want with Edit in Place in the works?

**Comment by dcarsey** [comment]
@mbwatson @luthfib  XL likes to mess w/ the CSV upload data and it creates problems, especially WRT date format.  Please correct me if I'm wrong.

**Comment by luthfib** [comment]
@dcarsey Keep in mind that supporting .xlsx format (excel) would be quite a large task, as we currently use native lib in Python to perform the CSV operations. More than likely this would require using new library and would more than likely be a lot of new code.

**Comment by dcarsey** [comment]
discussed this with Jackie on 7-22-2021 and this feature is no longer desired.
