### ISSUE TITLE
Add error-handling for CSV upload pre-parsing

### ISSUE THREAD

**Issue by krobasky** [RENCI/ctmd#338]
Do some pre-processing on each of the 5 CSV uploads to determine if they are :
1. CSVs
2. Have the correct number of columns
3. Have the recognizable fieldnames in the header portion
4. Have the right number of fields per row
5. Have well-formatted fields in each row, with appropriate values
If any of the above fail, return a useful message to the user.
If pass, check all return values, and if anything unexpected happens, roll-back the transaction and provide feedback to the user.
6. Have date parsing to ensure users upload complete dates. ( Perhaps some kind of dialogue box to prompt the user, such as "Not all of your dates are in mm-dd-yyyy format. Are you sure you want to continue?" , would be useful)

**Comment by krobasky** [comment]
Pay special attention to special characters and duplicate ids (see Jackie's csv that failed)

**Comment by rajshruti18** [comment]
Resolved by https://github.com/RENCI/ctmd-dashboard/pull/228

**Comment by dcarsey** [comment]
Nos. 2-4, above, are now a part of #462 

Have the correct number of columns
Have the recognizable fieldnames in the header portion
Have the right number of fields per row
