### ISSUE TITLE
Connect empty fields in STUDY PROFILE report screen

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#339]
On the STUDIES tab 
Study ID Number 171
little green box / ACTIONS / 
STUDY REPORT for SPIRRIT has some blank fields.

[See this example.  ](https://www.dropbox.com/s/r4e3kjgmlthmf59/SPIRRIT%2012-14-2020%20upload%20comparison%20of%20fields.PNG?dl=0)

Yellow highlighter indicates fields that require data from the PROPOSALS table.  (check to see why this data is not coming through -- have field names been changed?)

Red pen indicates missing data on the screen, but the CSV template contains data that should have imported in those fields.

[Here is the CSV template that Jackie uploaded. ](https://www.dropbox.com/s/ktsx0orgximlzqv/Study%20profile%20REAL%20data%20SPIRRIT%2012-14-2020.csv?dl=0)

**Comment by luthfib** [comment]
Most of these are fixed. The missing fields now are:

- TIC
- RIC
- Date Funding was Awarded
- Phase
