### ISSUE TITLE
Prevent outside requests (other than those from TIN) from hitting API

### ISSUE THREAD

**Issue by mbwatson** [RENCI/ctmd#340]
let's restrict access to the Internet on all containers, except:

- let the API see requests from the TIN dashboard
- let the front-end container see the outside world.

here are some promising resources to remember:

- https://netbeez.net/blog/networking-with-docker/
- https://forums.docker.com/t/internal-network-between-containers-without-external-network-access/41751/7
- https://stackoverflow.com/questions/39913757/restrict-internet-access-docker-container

don't forget to ensure there are no clashes with the changes made when resolving that ip issue (last year?).

**Comment by luthfib** [comment]
I don't believe this method will work, because the one that is making the requests at the end of the day is the client. I think what we will need to do is have an auth method into the api, so that when someone isn't authenticated they can't make requests against the api.

**Comment by luthfib** [comment]
I don't believe this method will work. This would work if you were making the requests from the frontend container but because the one that is making the requests at the end of the day is the client then it doesn't work,. I think what we will need to do is have an auth method into the api, so that when someone isn't authenticated they can't make requests against the api.

**Comment by mbwatson** [comment]
@luthfib  agreed--auth on the API would be best.

in the mean time, i wonder if we can patch the security concern from the TIN dashboard requesting that graphic (which _is_ a request directly to the CTMD's API). perhaps there should be a third bullet:

- allow all requests inside the containerized network

we can define a network that ensures all requests to the API either come from within the application containers (spooky, the calls are coming from _inside the house_), but I'm not sure if there's a way to also allow requests the TIN dashboard.

**Comment by luthfib** [comment]
Per discussion in our meeting we will be:

We will pass a code to auth-fuse service from our api, which will hit the Vanderbilt auth flow to verify if a user is logged in. If the user is logged in then we will pass the request along if it they aren't logged in they will be prompted to log in.
