### ISSUE TITLE
Confirm w/ Jackie her ability to successfully upload enrollment data to Stage

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#341]
Jackie had trouble uploading this enrollment data.

https://www.dropbox.com/s/ymtagdcdpxdscwb/Spirrit%20Enrollment%20from%20Jackie%2012-16-2020%20did%20not%20work%20for%20her.csv?dl=0

I adjusted the date format column and I also had trouble with it.
https://www.dropbox.com/s/aj4pz239dyooyc5/Spirrit%20Enrollment%20template%2012-16-2020%20changed%20date%20format.csv?dl=0

Then on 12-18-2020 I was able to make it work.  Dawn is checking w/ Jackie to see if she can get it to work now.
Kimberly> 
Maybe create a document with clear instructions on how to upload each csv on the uploads page

Close this ticket when:
Jackie can upload sites and the enrollment data csv types 2x without any error

**Comment by dcarsey** [comment]
We were not able to reproduce failure in regard to upload or any problems with dates in the uploaded CSVs.  
I was able to upload date in mm-dd-yy, mm-dd-yyyy, and 9-SEP-19 formats.

We think the problem lies in formatting that follows the copy/paste from an XL spreadsheet.
Encouraged Jackie to grab a fresh template from CTMD , copy/paste data, re-format cells w/ dates to mm-dd-yy OR mm-dd-yyyy and see if upload is successful.

Dawn offered to be present for all attempts to test this to help w/ troubleshooting.

**Comment by dcarsey** [comment]
Documentation to assist with upload process.

[https://docs.google.com/document/d/1rJh_y5v_6wusChOMzXfwP8PCQBDJ78TkoCXW4VyZCJ8/edit?usp=sharing](url)

**Comment by dcarsey** [comment]
Confirm that Jackie can successfully upload

- [ ] CTSA data
- [ ] SITES data
- [ ] STUDY PROFILES data
- [ ] STUDY SITES data
- [ ] ENROLLMENT data

**Comment by mbwatson** [comment]
@dcarsey did this get worked out?

**Comment by dcarsey** [comment]
@mbwatson Still making (user) errors as of this past Tuesday.

**Comment by dcarsey** [comment]
Jackie seems to be fully trained and is training others now.
