### ISSUE TITLE
Rename the metric Queries per eCRF

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#347]
- [x] The metric Queries per eCRF needs to be RENAMED:   Queries per total data elements 
- [ ]   Data elements needs to be added as a field 
- [ ]  Data elements needs to be added to the STUDY PROFILES template 
- [x]   Luthfi - please see how the eCRF metric is computed
- [x]   This ticket is also related to #95 and #335

**Comment by luthfib** [comment]
Closing this ticket and creating a new ticket for the two items that are not done. #350
