### ISSUE TITLE
Add Data Elements and lost to Follow up

### ISSUE THREAD

**Issue by luthfib** [RENCI/ctmd#350]
Close this ticket when the following are done:
- [x]  Data elements needs to be added as a field 
- [x]  Data elements needs to be added to the STUDY PROFILES template 
- [x]  Lost to Follow Up
- [x]  Lost to Followup needs to be added to the STUDY PROFILES template
- [x] Update docker image

This ticket might provide more context if needed. #95

**Comment by rajshruti18** [comment]
Added above two fields to the 'Sites' table in the mapping. https://github.com/RENCI/HEAL-data-mapping/commit/ec540666c1cba6570fc01d5a6104547ef1b18cb3
https://github.com/RENCI/HEAL-data-mapping/commit/17c84a5962825f15a7e222d97ebb5b019ab088e1
