### ISSUE TITLE
5 fields in proposal table are blank (have no data in them)

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#357]
5 fields in proposal table are blank (have no data in them)
Find out where they are pulling from and address this.

-  [ ] grant award date
-  [x] approved for comprehensive consultation
-  [x] resource:  recruitment & retention planning
-  [x] resource:  single IRB
-  [x] resource:  standard agreements

^^^ Note:   Jackie suggested the names for these resources may not be 1 to 1 (name change in resources.... like that graphic we dealt with) could be causing issues.

**Comment by luthfib** [comment]
actualGrantAwardDate maps to release_of_funds_2 which is empty in the redcap database. This means it is an issue on their end.

**Comment by luthfib** [comment]
"approved for comprehensive consultation" was renamed to "Recommend for Comprehensive Consultation", and that is a status under ProposalStatus column, which means I do not think we need "Recommend for Comprehensive Consultation" as a column as it will appear under ProposalStatus when present

**Comment by luthfib** [comment]
Closing. Opened #364 to solve the first bullet point
