### ISSUE TITLE
Grant Award Date is Blank 

### ISSUE THREAD

**Issue by luthfib** [RENCI/ctmd#364]
Grant award date is blank in the proposal table. The field is also blank in Redcap. We have reached out to Michelle to see if we can get that issue resolved. Linked to #357

**Comment by dcarsey** [comment]
Michelle confirmed that actualGrantAwardDate is correctly pointing to release_of_funds_2
She said there IS data in REDCap on this field, and included the following report.  Note far right column in this spreasheet for the data available in REDCap for this field.

[https://www.dropbox.com/s/04i7j5tg1ommkhq/2021%20Jan%2019%20checking%20REDCap%20release%20of%20funds%202%20data.csv?dl=0](url)
