### ISSUE TITLE
edit enrollment template fields

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#366]
Change Proposal ID and ProposalID to
REDCap proposal ID 

Put suggested date format in Date field  (mm-dd-yyyy)

Remove the word REVISED from both lines for PROJECTED SITES

**Comment by luthfib** [comment]
After discussion with @rajshruti18 decided I will only be changing the top field of the csv. Changing the second row of either of those will cause too many repercussions and unneeded work.
