### ISSUE TITLE
Change enrollment graph to bar graph

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#367]
Visual design change to be made to expected sites and actual sites info.  Place in bar graph format instead of line graph.

Make it clear which bar is expected vs. actual sites activated.  

Keep actual enrollment (patients enrolled) as a line running across the visualization.

Here is an example:
https://docs.google.com/spreadsheets/d/14s7-yQg5WcCurlnNpTb9iYgXHe3HuhIGMvdM9K7MN-c/edit

Complete by Feb 2 so that Jackie can give feedback at next Duke TIC meeting.

#330 On enrollment graph, please shorten/abbreviate all long month names (Jackie's request).
January = Jan
February = Feb
August = Aug
September = Sept
October = Oct
November = Nov
December = Dec

**Comment by rajshruti18** [comment]
Made changes to abbreviate month names. Need feedback from @davidborland . https://github.com/RENCI/ctmd-dashboard/pull/170

**Comment by davidborland** [comment]
Implemented
