### ISSUE TITLE
Phase Field Value seems to be incorrect in Study Profile

### ISSUE THREAD

**Issue by luthfib** [RENCI/ctmd#373]
The phase value that is coming in seems to be incorrect in the Study Profile page, look into it.

**Comment by dcarsey** [comment]
Re-opening the ticket.  Phase is still not displaying the right data.


171 should be Phase 3
Luthfi will talk to Shruti who will know what it maps to.  
Study_vumc_ric1ase
The 4 might be a code that maps to something else
