### ISSUE TITLE
FUNDING STATUS in proposals table - make sure it's pulling in the right data

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#381]
Funding status (proposals table) is pulling from wrong spot ? maybe from proposal submission form i/o new funding source - but it’s actually 3 fields:  
sometimes studies don’t get funded 1st round and they re-submit and they have the potential to get funded on a subsequent attempt/submission
Places to check
Funding - intake form
New_funding_source - updated form
Updated_funding_status - tied to grant resubmission and only populates when new funding source = 4 and resubmit = 1
Factor in these 3 variables listed above and know that funding status trumps each one that comes after it

**Comment by rajshruti18** [comment]
Made required changes to the mapping. https://github.com/RENCI/HEAL-data-mapping/commit/6a979aeac701b891f1bd045718010e1202feea74
