### ISSUE TITLE
optional "Connect to CTMD" button 

### ISSUE THREAD

**Issue by krobasky** [RENCI/ctmd#384]
Add an "optional" blue button that says "Connect to CTMD" that will be rendered if the query payload includes "button=yes"; the trick will be to make the button "clickable", sending the viewer to the correct server (e.g., ctmd, heal, or stage-ctmd)

related to #380

**Comment by krobasky** [comment]
![image](https://user-images.githubusercontent.com/413166/108375362-df181b00-71cf-11eb-8051-10e1a33d8d48.png)

**Comment by mbwatson** [comment]
this is on the TIN side, no?
