### ISSUE TITLE
Change max and range on enrollment data slider

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#397]
1.  Jackie will discuss w/ her team and determine what the MAX enrollment data slider option should be.  It is currently set at 2.0

2.  The range on the slider may need to shift based on the designated enrollment rate.

Current thoughts:
Can the user select the range that is displayed?
The slider is currently broken into 20 segments (.1, .2., .3... all the way to 2.0).  Is it useful / doable to have those 20 segments adjust automatically based on the enrollment rate the user selects?

3.  Get David's thoughts / possibly come to TIC call to discuss options / collect requirements.

**Comment by krobasky** [comment]
maybe make the "max" on the slider a configurable value they can type in?

**Comment by davidborland** [comment]
Could just make it a spinner instead of a slider and they can type in whatever they want...

**Comment by dcarsey** [comment]
Per Jackie 5-13-2021

Range for spinner:  .1 - 1000 (or 999)
To move by increments of .1 but able to ENTER the number and THEN spin from there by .1

**Comment by rajshruti18** [comment]
Implemented via https://github.com/RENCI/ctmd-dashboard/pull/216
