### ISSUE TITLE
usable codebook

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#407]
similar to #323

In the end, will they get a codebook? Tried to keep the field names the same even though they don’t really make sense. Now that we have it -- should probably start renaming them and make them human readable. For now, you can use the existing codebook because that’s what was used to create the tables. Will need to investigate the most usable way to get codebook info for Lori. There is a spreadsheet to search for a field and it will tell you where it can be found.

**Comment by krobasky** [comment]
can't be addressed because Theresa asked us not to publish any aspect of the Vanderbilt "secret sauce" in any way, and also this is a sensitive Duke/Vanderbilt issue, as far as I've been told. Closing ticket based on the information I currently have.
