### ISSUE TITLE
Enrollment graphic legend months don't match the data

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#415]
From Jackie:

The enrollment graphic legend months don’t match the months of the data. I’m hovering on Sept, but it shows the data for Aug. Dec 2018 shows 0 for everything with the data going under January and then Nov and Dec 21 are squished together.

![enrollment data screenshot 03-30-2021](https://user-images.githubusercontent.com/47784445/113056446-cd844480-9179-11eb-9902-784791c89777.jpg)

**Comment by davidborland** [comment]
Do we have the data for this?

**Comment by dcarsey** [comment]
@davidborland I'll reach out and see if I can get that CSV upload from Jackie.

**Comment by dcarsey** [comment]
@davidborland  Here it is:

**Comment by dcarsey** [comment]
[https://www.dropbox.com/s/hb9bcwxb41rmn2x/Spirrit%20Enrollment%20data%20from%20Jackie%203-31-2021%20months%20do%20not%20line%20up%20properly%20with%20data.csv?dl=0](url)

**Comment by dcarsey** [comment]
4-15-2021 -- stakeholder meeting -- I shared this info w/ Jackie (from David)

WRT the data months not matching up with the axis months, this is because the dates for most of the data are on the last day of the month, and the axis is labeled for the first of the month by default, so it looks like they are mis-labeled, when really it is just that the bars/point are being drawn a day before the axis ticks.
This is also the reason why the last December is squished with November - the date for December is the 11th, instead of the end of the month.
COMMENT:  It should be pretty straightforward to place the ticks where the bars are (instead of a day later as they are now) and display the correct month for the data.
QUESTION:  Less clear what to do with the November/December case. Should we always assume that there will be at most one data point per month, and always show it at the end of the month (even if the provided date is in the middle of the month)?

Jackie understood David's response and is going to double-check, but  she suspects that it IS possible that there could be more than one data point per month.  Ex:  a fast-enrolling study e.g., COVID that has weekly enrollment targets

David -- I'll get an answer for you and we can go from there.

**Comment by dcarsey** [comment]
Sent to Jackie 4-15-2021

Hi Jackie,

Please see the attached image to see some adjustments that David made.  He has shifted the labels (not the data points) to fall between the tick marks.  The data points will still land approximately in the beginning OR middle OR end of the month space, based on what the data says (June 1 vs.15 June vs. June 24).  AND it will accommodate more than one data point per month in case it is a fast-enrolling study.  Those multiple monthly data points will be placed “according to the data” (beginning / middle / end).  

Note that data points at the end of the month will fall at the tick mark to the right of the month label.

Give it a hard look and see what you think.

![David's changes on SPIRRIT graph 4-15-2021](https://user-images.githubusercontent.com/47784445/114928665-dc692900-9e00-11eb-8ba8-e09647b52a71.png)

**Comment by dcarsey** [comment]
Jackie's response:

HI Dawn,

I think having the labels shifted makes I more confusing. I think its better with the labels on the tic mark


Dawn's response:

Ok.  So are you saying don’t make any changes – that it’s just user training?

Wanted to make sure David knows if he should pursue or not.

Thank you!

D


Jackie's response:

Yes I think so. If the label could include the day and not just the month (the label when you hover) that would help.

**Comment by dcarsey** [comment]
David added the hover function for the date.

Dawn to Jackie:
David has done the following:

the labels were shifted to the end of the month
when you hover, you will be able to see the full date (month, date, and year – not just month/year)

Jackie's response:
Hi Dawn,

I like the hover showing the full date.

The problem with shifting labels to the end of the month is that it looks good for how I have set it up but other studies may have the beginning or the middle, its hard to know. So I would keep in the middle as it was.

**Comment by davidborland** [comment]
Implemented this version, showing full date (day and year) for January:

![image](https://user-images.githubusercontent.com/289957/115249273-72010300-a0f6-11eb-8292-884f5527403f.png)

Jackie's response:

Hi Dawn,
I think that looks good, thank you!

Closing for now.

**Comment by davidborland** [comment]
Merged with 2.0
