### ISSUE TITLE
Double-check enrollment data with only ONE site

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#421]
This enrollment data (see link below) is uploaded on the HEAL site.  The user who uploaded it was new, and so he wasn’t used to how things operate, but I think he thought the graph looked odd.

Jackie thinks it’s because there is only ONE site for this study and there will not be any other sites for it.  

If you could just double-check that the data seems to be in order and that the graph is behaving properly and provide any insights / advice / future thoughts about such a situation.

[https://www.dropbox.com/s/ptej2yau81vlnjh/Surgery%20Pal%20enrollment%20data%20one%20site%204-15-2021.csv?dl=0](url)

**Comment by davidborland** [comment]
This is what it looked like:

![image](https://user-images.githubusercontent.com/289957/115249589-c0ae9d00-a0f6-11eb-9a4b-2184bfd1a3cb.png)

Adjusted the legend to this (Move legend in front and add a border and transparent background:

![image](https://user-images.githubusercontent.com/289957/115249775-efc50e80-a0f6-11eb-98e5-d29810730c76.png)

Waiting for feedback from Jackie

**Comment by dcarsey** [comment]
Jackie looked at the enrollment data and the graph for this user and said that the graph looks as expected.

David made a suggestion / tweak or two and Jackie didn't think any changes were warranted.

**Comment by davidborland** [comment]
Does this mean go back to the previous version with the legend hidden behind the bars for this use case, or go with the new version with the legend in front + background and border?

**Comment by dcarsey** [comment]
@davidborland It means you can restore it to the original way you had it in the CTMD.  Legend hidden behind the bars.

Thank you.

**Comment by davidborland** [comment]
She would prefer it to be behind the bars? That seems odd to me...

**Comment by davidborland** [comment]
Version with legend border now in 2.0. Closing for now, but we can reopen if we need to.
