### ISSUE TITLE
Connector button from TIN to CTMD is not displaying on TIN site

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#448]
At first we thought it was a browser issue.

KR suggested it could be related to the tx-autht server update.

Matt thinks it could be a bug in the authentication process.

Email chain w/ Michelle - not sure it's helpful, but here it is:

FROM DAWN to Michelle:
Hi Michelle,
 
We have been digging deeper into the TIN / CTMD connector button issue, and the team has asked me to do some further checking with you.
 
Can you please send the html code that you’re using to embed the image?  It will help us to determine what it is you’re expecting from our side.
 
Thanks, Michelle.
 
D
***
FROM MICHELLE to Dawn
Hi Dawn,
 
That’s the URL we were given for the image link and it just loads up after a 60 second timeout with this:

https://ctmd.renci.org/api/graphics/proposals-by-tic?code=iaZ9cdTuzm

KR's internal comments:

I may be wrong, but I think ‘code’ is a session code, and will time out, so of course they’re not going to be able to retrieve the image if they just hard-code in a value.
 
Loop Matt into the conversation, he’ll give you all the words, and will be more informed on the details than I am.

**Comment by dcarsey** [comment]
Help ticket submitted to ACIS:
We have a problem on our CTMD site and our digging has led us to suspect that we have a mismatch in our certificates.
Can you please check the following VMs to see that they all match and if not please advise / update the ones that need to be updated?
Auth-fuse.renci.org
Dev-auth-fuse.renci.org
Stage-auth-fuse.renci.org
Ctmd.renci.org
Stage-ctmd.renci.org
Dev-ctmd.renci.org
Heal-ctmd.renci.org
From: Kevin Otte, RENCI ACIS
Answer #1 from Kevin
I checked all the sites listed and found that auth-fuse and dev-auth-fuse seem to be misconfigured. They are presenting a correct server certificate, but not the intermediate certificate. These appear to be handled by docker-proxy, so I'm not sure how to correct this.
Since you are using the Digicert certificate, their instructions might provide a pointer in the right direction:
https://www.digicert.com/kb/ssl-certificate-installation.htm
You may also wish to consider migrating to a Let's Encrypt certificate at this point.

Answer #2 from Kevin
Further investigation finds the certificates live in /opt/certs on the host and are mapped into the container for use. I believe I can update the certificate bundle there and do a "docker restart tx-autht_txautht-nginx_1" to have it pick up.
I noticed the certificate on dev-auth-fuse was copied over from dotdsi.renci.org. While this is functional, it would be a problem if the certificate ever needed to be reissued. ACIS would not have any record of this usage of the certificate. I'll plan to issue a new certificate to cover all of the CTMD machines to help with this.
I'm 99% sure this will all work, but there's that small chance the Docker container won't restart correctly, in which case I would be uncertain of the next steps. I can do dev-auth-fuse now, and if it works move on to auth-fuse, or we can wait until after the break when folk are back.

--
From Hong:
I think you can run down.sh in /var/opt/auth/txautht if containers are not down already, then run up.sh in the same directory to bring all containers back up. Yes, once the certs are updated, running down.sh followed by up.sh should have new certs take effect in the container.
The path suggested by ACIS left open the possibility that after they installed the fix, the container may not come up on its own.

We’ve opted to wait until the first week in January and THEN we will give the green light to Kevin Otte to move ahead with the plan they suggested (see below).

**Comment by mbwatson** [comment]
this was solved by adding a missing import and figured out by improving logging in api/app.js.
