### ISSUE TITLE
Create a stage-heal-ctmd server

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#452]
To test our code before launching to production on the HEAL site, we need a STAGE-HEAL server.

close when server is running with live HEAL data

**Comment by krobasky** [comment]
step 1: request help@renci.org for stage-heal-ctmd.edc.renci.org, with same ports open and configuration, users as heal-ctmd.renci.org. cc me

**Comment by dcarsey** [comment]
Dawn double-checked on the status of this project.  Robert Jones has been on vacation but hopefully moving forward now.
