### ISSUE TITLE
Jackie can't see download button on CTMD-configured, v2.1.1 stage server

### ISSUE THREAD

**Issue by krobasky** [RENCI/ctmd#457]
The requirement is:
HEAL people need to be on access list
CTMD people do not

To close this ticket:
- [x] figure out which developer can/should address this ticket
- [ ] install fix to dev server
- [ ] set env var IS_HEAL_SERVER to true and restart API - confirm people on the access list CAN see download button, and people NOT on the access list cannot
- [ ] set env var IS_HEAL_SERVER to false on the dev server and restart API - confirm that somebody that is NOT on access list, but that is logged in through authserver CAN see the download button
- [ ] PR to master has been approved and merged
- [ ] Shruti has created a new patch release (2.1.4?) and updated the release documentation, and roll stage forward to 2.1.4
- [ ] Jackie has accepted 2.1.4 on stage (which will include 2.1.2, 2.1.3 patch functionality and fixes)

**Comment by rajshruti18** [comment]
@krobasky I can take up this ticket but I am not very sure as to what will the PR as mentioned in bullet #5 have. Can you please explain.

**Comment by dcarsey** [comment]
This has been solved.
