### ISSUE TITLE
STUDY tab is missing a field / tickbox

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#460]
SITE NUMBER is a missing tickbox / column on STUDIES tab:   add column - to be pulled from study-sites upload.

It may not always be a numeral -- it needs to allow TEXT.

**Comment by dcarsey** [comment]
#441 is similar -- it involved adding tickboxes / fields to the same tab

**Comment by adrian-renci** [comment]
closed here -> https://github.com/RENCI/ctmd-dashboard/pull/231
