### ISSUE TITLE
Create a place where users can view metrics for any study

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#464]
Determine location.

Create a place where users can view metrics for ANY study, by typing in the proposal ID (study) number.

Currently, you have to be on the study tab for a particular study to see its metrics.

This seems to be the visual solution for #396

**Comment by dcarsey** [comment]
@davidborland says:
Potentially more complicated. A potential solution might be to just add a dropdown to the study profile page that lets the user quickly switch between studies. If that works, that should be pretty easy.

**Comment by davidborland** [comment]
A few possible options for comparing metrics across studies. All of these would use the current Studies page.

1. Parallel coordinates
![image](https://user-images.githubusercontent.com/289957/183724103-256829ea-4603-4101-b0a9-7a4b4deec038.png)

2. Heat map
![image](https://user-images.githubusercontent.com/289957/183724172-be94f607-ae2c-4ea7-863f-357c39e1c3b3.png)

3. Tabbed bar charts
![image](https://user-images.githubusercontent.com/289957/183724218-43c7ce51-bfb8-458c-be43-0087d029a59e.png)

4. Add metric fields to existing table, enable toggling on and off (no image)

**Comment by dcarsey** [comment]
Do not create new tabs, but rather install a button on the STUDIES tab and another one on the SITES tab.
Buttons for different views:
•	default view (currently as is)
•	show metrics button
•	Can add other buttons/views over time
In order to render the tables / views quickly
•	each button will be designed to be a preset
o	data/fields already established
•	the data would only be calculated once and then placed in a store, making it available for fetch from all the places that pull in this data
•	Would still have the CSV export function for the tables
I want to confirm something that Jackie said:
“Aside from all the views what we need is the ability to download metrics (date of irb submission, date of irb approval, date contract sent, date contract approved etc) by site for multiple studies or all studies in one spreadsheet. Now if we want to do that we have to download one by one and the manually put into one spreadsheet.”
Jackie – do you mean that you want the metrics to report out the date of IRB approval, OR INSTEAD, the metrics that pertain to IRB approval (sIRB approval time, which reports back # of days); and then the same question for the other examples you gave (date contract sent, date contract approved…. Do you want the DATE OR the # of days it took to achieve that milestone?)
Now following up on something that Stephen said: 
“As I think about this, it seems like there could be a relatively straightforward way to achieve both of your options 1 and 2…. On the “Sites” tab, it’s already supposed to list each site multiple times for every study it’s associated with.  So if, theoretically, Children’s Hospital Los Angeles is a site on Kids MoD PAH, STRESS, and PREVENTABLE, there should be three rows for CHLA in the “Sites” tab, one for each study. In theory it seems straightforward enough to add the metrics (and allow toggle on/off) to the “Sites” tab to view site metrics for individual studies in one place (your Option 1). You could perhaps also have a site master or “averaged” row – unsure what to call this – for each site where metrics are computed across all studies. And maybe the individual study-site rows collapse under the master row, if that makes sense. This is your option 2. Would be something like the below table. Stephen:  I highlighted your requested average for the site in yellow, below.  This is also perhaps useful because an average across a small sample size can be highly impacted by outliers, but you’d be able to readily see the individual study-level metrics that go into the averaged metric.”
From Dawn:  Yes - I’m sure they can do that.  I’ll add it to the list of requirements for it.

**Comment by dcarsey** [comment]
Discussion:  [https://docs.google.com/document/d/1lElV4eMZ9-PT3hBfjZikmzvsYK1Hnpk03N-TfekELJw/edit](url)

**Comment by dcarsey** [comment]
Also read #522  before proceeding

**Comment by dcarsey** [comment]
![image](https://user-images.githubusercontent.com/47784445/210433616-a0eb1745-6ea8-41a9-8d37-49c97a9d6e10.png)

Right hand green box only displays these items (and we should come up w/ a better label for it, not ACTIONS)
study profile
Donuts
enrollment graph

LEFT hand side 

- has tickboxes that can be checked on or off to display aggregated study data (metrics list of 10) - w/ master switch at top
- Has tickbox that will show a listing of all study-sites, with each one having a tickbox that can be checked/unchecked + a master switch that can switch them all on/off
- Additional tickbox to click that will displayall 10 metrics for each study-site 10 metrics (w/ master switch at top) 
- The 1st tickbox will open and display the metrics in bold to indicate that it is the aggregated data, as opposed to individual study-site level metrics
- The 2nd symbol will open and display the same metrics, but listed individually for each study-site (metrics list of 10)
- ** NOTE ** This info is currently viewed after you click the green box, but I’m suggesting we move it to the “front page”

Downloading

- allow downloading of aggregated study data (1st caret info for all studies)
- And individual study-site data for all studies


Expand all?

- Tickbox in front of each
- Do we need a tickbox at the top that will automatically open all studies AND display a “checked” tickbox for each study + each study-site for them?
- Then that feature needs to work in reverse:  can collapse and close all studies


Suggestions and feedback from David & Matt:

Filtering - show only ticked boxes 

Front page vs behind the green box

2 sets of buttons metrics vs. other designated fields

create an uber table:  ability to click on and off what they want to see
Analysis page where they can see what they want from the uber table (with un-checked info filtered out) and compare that data


When using dashboard, what tasks are they performing?
Are there groups of columns they typically want to see together?
ex:  Pre-set buttons ex: (metrics + identifying info that goes with it)
Are there identical ways that they look at the data – searching for the same certain things (and excluding others)

What is the ultimate goal:  that will help us design something flexible

Can definitely add dump CSV to see all data

**Comment by dcarsey** [comment]
[site-metrics mock-up.csv](https://github.com/RENCI/ctmd/files/11297547/site-metrics.mock-up.csv)

^^ mock-up of CSV by David (round 1)

Info to report back in the CSV:

We need the following

Proposal ID 
Protocol Name :  edited -- PROPOSAL name, not protocol name

All the metrics: available in the study download 
Protocol (Short Description)
Site ID
CTSA ID
Site Name
Site Number
CTSA Name
PI
Date Protocol Sent
Contract Sent
IRB Submission
IRB Approval
Contract Execution
Site Activation
LPFV
Enrollment
Patients Consented
Patients Enrolled
Patients Withdrawn
Patients Expected
Protocol Deviations
Lost to Follow Up
Protocol to FPFV
Contract Execution Time
sIRB Approval Time
Site Open to FPFV
Site Open to LPFV
Percent of consented patients randomized
Actual to expected randomized patient ratio
Ratio of randomized patients that dropout of the study
Major Protocol deviations per randomized patient
Number of Queries
Queries per patient

They want to be able to use the cells with just numerals if possible so they can analyze the data easily.
24 days should just be 24
50% should just be 50
missing data should report back as blank

**Comment by dcarsey** [comment]
Feedback from Jackie 4-25-2023

1. 2nd field on CSV  should be PROPOSAL name (not protocol) - you only need to change the column header, the data being pulled in is correct
2. We inadvertently omitted one of the requested fields:  please add CTSA NAME
3. She forgot to request this field.  Can you please add FPFV?
4. Typo in one of the field names, please change major protocol deviations per randomized patients to singular form:  major protocol deviations per randomized **patient**
5. Dawn will double-check that zeroes in the site are reporting back as zeroes and that missing values are reporting as blanks
6. The enrollment column is fine as is (with BOTH ratio and percentage together)
7. The fields that are percents should be a whole number.  Ex:  .53 should be 53; 1 should be 100
8. Where decimals are carried out several places, truncate it to 2 places past the decimal.
