### ISSUE TITLE
Create patient enrollment data (round graph) similar to site activation and site enrollment

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#473]
CTMD (and HEAL):  Use same circle thingy to indicate: 25% patients enrolled, 50% patients enrolled…. The same way we do for sites activated
Might be some tweaks to how it’s being calculated
Originally based it on study-sites w/ expected enrollment
Not sure how to calculate denominator for enrollment (what is used)
Jackie will provide more info on this as feedback comes to her.

**Comment by dcarsey** [comment]
Per Jackie:  Use Enrollment Goal from study profile as denominator.

**Comment by mbwatson** [comment]
@dcarsey i'm shooting for a layout like this:

![Screenshot from 2022-05-27 17-33-32](https://user-images.githubusercontent.com/6019870/170791997-ff537e10-9cc6-4da7-95c0-90b3c7475b51.png)

thoughts?
