### ISSUE TITLE
SITES upload over-writing removing data from STUDY-SITES

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#474]
On 10-1-21

Jackie added new places to the SITES file and uploaded it
It removed ALL but 3 study-sites for SPIRRIT
It removed ALL study-sites (3) for Sildisafe
It removed ALL study-sites (1) for Pediatrix

Spring/Summer 2021 = when Adrian joined us, we had the same problem but in the opposite direction:
#429 
STUDY-SITES uploads were removing SITES from the list

We determined that decimal numbers in whole number fields were causing the problem.

Current status (10-7-21)
CTMD has been restored to accurate data with
SITES uploaded
SPIRRIT uploaded
No data yet has been added for Sildisafe or Pediatrix.

Blocker for our stakeholder:
JHU has uploads ready to go but have been told to hold off
Utah has been asked to upload but they’re not quite ready
Also holding off if they get ready

**Comment by hyi** [comment]
This has been fixed by this https://github.com/RENCI/tic-map-pipeline-script/pull/21 and https://github.com/RENCI/tic-map-pipeline-script/pull/20, closing.
