### ISSUE TITLE
Debugging SITES upload - will not behave with SITE 186 and higher

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#475]
Related to #474 :  when this SITES upload (see attachment) is added to the dashboard, it removes data from the following places:

- SPIRRIT study-sites go from 48 to 3
- Sildisafe study-sites go from 3 to 0

[sites-template master_up 29SEP21 EDITED with TEST for duplicate site name.csv](https://github.com/RENCI/ctmd/files/7324370/sites-template.master_up.29SEP21.EDITED.with.TEST.for.duplicate.site.name.csv)

Sites 1-185 in this file might be fine and the problem MIGHT be in 186-235.  I tried to break down 186-235 into sections and it removes study-sites when uploading sites 186 and higher.

**Comment by hyi** [comment]
This turns out to be a docker deployment issue and has been fixed by rebuilding production server. Closing.
