### ISSUE TITLE
Add documentation for PR to edit doc for deployment

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#479]
added a PR to edit doc for deployment, we needed a $USER in front of docker-compose. We also needed to change permissions on db/data, I'm not quite sure how to document that because the steps we used were really wonky! but it needs to be doc'd.

**Comment by hyi** [comment]
Since the PR https://github.com/RENCI/ctmd/pull/478 addressing this has been merged and deployed, closing this issue.
