### ISSUE TITLE
Add 2 fields to study profile CSV and study profile report on screen

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#490]
Add this field:  contract type (free text) in study profile upload template - NEW Field, not replacement
Display:  Reports out on the study profile page
30 characters ?? OR match to existing proposal fields?

Add this field:  Number of fields per casebook
New field to add to study profile upload template
Display:  Reports out on the study profile page
Should be numeric

**Comment by mbwatson** [comment]
adding new fields `contractType` and `fieldsPerCasebook`
