### ISSUE TITLE
EHR based cohort assessment tickbox has no data

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#495]
EHR based cohort assessment is no longer an option for PIs / proposals to select.
This resource was changed to EHR-based tools and resources -- which we DO HAVE on the home page of the CTMD, bottom section, bar graphs.

Check mapping between RENCI and REDCap
Dawn to check w/ Michelle about this

Front page is correct / tickboxes are wrong.

**Comment by dcarsey** [comment]
@davidborland Please read the track record on #300 for a refresher on a related problem.  Thanks!

**Comment by davidborland** [comment]
Fixed
