### ISSUE TITLE
Server activity tracking 

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#499]
Google analytics
GA4 or Mixpanel
How long the user was on?
Where they came from? ex: TIN
Which Google account should be used?
Txscience email?
Create new Tx science gmail account
PW shared via chat

**Comment by krobasky** [comment]
The quick/easy solution is to add the following code from google to a 'footer' component somewhere:
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src=https://www.googletagmanager.com/gtag/js?id=G-JEXX407FCJ></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-JEXX407FCJ');
</script>
```
I'm not sure if there is a more elegant solution that fits better with react.

**Comment by krobasky** [comment]
At some point, we should create a "Usage stats" ticket that allows us to get at the impact in more granular detail.
