### ISSUE TITLE
Set overnight sync to 0300

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#500]
Duke would like the overnight sync to occur at 0300.  This will allow their west coast users to have decent access without scheduled jobs running up until midnight, and east coast user early birds will have a data refresh by 0600.

Of note:  originally PLs were required to submit monthly updates of their data (maybe in the TIN, I'm not sure), but this has now been bumped to QUARTERLY updates.  So the uploads will be happening less often than originally thought.

**Comment by krobasky** [comment]
release 2.8 on ctmd.renci.org
