### ISSUE TITLE
Prod has no data

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#515]
On 7-15-22, Jackie notified us that prod had no data.

Things we discovered in the debugging process:

prod:  redis worker doesn't start up; prod has no data
trying to restore from a good backup that works on stage, we can manually start the worker redis client in pipeline container, worker takes item off queue, but pipeline still won't perform the queued restore function
Error message:  pipeline container cannot connect to redis server
determined it is not a network issue
was able to get dev past the redcap download error but data sync ran into a new error we haven’t seen before
Exception in thread "main" org.apache.spark.sql
AnalysisException: Detected implicit cartesian product for LEFT OUTER join between logical plans
Discovered the “device or resource busy error” for redcap_export.json file inside pipeline container is owned by a user with the same uid and gid as web user on the host
When Hong manually triggered data sync on stage, the data sync failed at the initial step trying to download redcap data -- PR might have solved it?
can successfully manually run the same csvsql command to ingest csv files one by one into our database
Data sync appears to fail on prod at the last step when ingesting csv files into database

**Comment by hyi** [comment]
[This PR](https://github.com/RENCI/tic-map-pipeline-script/pull/29) has been created to address this issue and the fix has been tested on dev-ctmd. Once the PR is merged, a new image with a new tag can be built and pushed to dockerhub and we can then test the new image on stage before deploying it to prod.

**Comment by hyi** [comment]
[The PR](https://github.com/RENCI/tic-map-pipeline-script/pull/29) mentioned above fixed the locking issue in the code which used to work but did not work any more a while ago on prod. The fix was tested on dev and is a more robust fix than the workaround currently deployed on prod with logging info statements added to break the dead lock.

**Comment by hyi** [comment]
Fixed. Closing.
