### ISSUE TITLE
Add 3 new study profile fields:  Comments, Project status, date of update

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#521]
to display on study profile screen
add to CSV template
tickboxes?

1. Add a Comments field, ex: updated study-sites, strange things that happen
2. Project status:  dropdown would be best - but if not, then free text field
3. date of update

**Comment by mbwatson** [comment]
@hyi the fix here will be reminiscent of the work for [#490](https://github.com/RENCI/ctmd/issues/490), so we'll have to coordinate a bit. 

i'll make changes to the Study Profile CSV template, and i suppose we'll need database and mapping changes on your end to support these new data.

- **Comments**: this ffield just feels like a free text
- **Status**: we can't do a dropdown in the CSV, but we could either (1) provide an enumerated list of options in the top row summary field or (2) just do free text. @dcarsey do we already know what options they'd want to use for this field?
- **Date**: a date

**Comment by hyi** [comment]
@mbwatson Yes, we'll need to coordinate between backend and frontend for this. Another related issue is with our current database backup/restore which does not work for new field addition initially. I have all details outlined in slack. Before that issue is taken care of, manual hack is needed to update database schema directly to add in new fields after the initial data restore which will restore the old database schema and override added fields.

**Comment by dcarsey** [comment]
@mbwatson Looks like a typo in the updated date field name.  updatedDate follows your pattern

**Comment by mbwatson** [comment]
i don't think she needs to care what our database fields are called. but she should weigh in on what the column description says in the template

**Comment by dcarsey** [comment]
@mbwatson They like your idea better because date last updated can be different from date of most recent upload.

**Comment by mbwatson** [comment]
@hyi i've gone ahead and added the three columns mentioned above to the Study Profile CSV template:


-    `comments` - free text
-    `projectStatus` - free text
-    `dateLastUpdated` - date

we can certainly alter those names if you've got better ones in mind.

**Comment by mbwatson** [comment]
@hyi that sounds like a great plan!

i've been working on the branch [521-add-3-new-study-profile-fields-comments-project-status-date-of-update](https://github.com/RENCI/ctmd-dashboard/tree/521-add-3-new-study-profile-fields-comments-project-status-date-of-update).

**Comment by vladimir2217** [comment]
@hyi if you need we can have a meeting regarding schema change and data restore

**Comment by hyi** [comment]
@vladimir2217 Sounds good. Let's make it a discussion topic as part of the next release process. We can nail it down on Tuesday when you roll this out to stage (or we do it together if needed).
