### ISSUE TITLE
If the CTMD is not pulling in REDCap data, check API token access

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#531]
https://redcap.vanderbilt.edu/

Click on
MyProjects

Then click on

TIN Database

Find and click on (left hand side of screen)
User rights

Check for expiration date on renci_tin

**Comment by vladimir2217** [comment]
redcap api does not throw an error. Instead it returns HTTP response with a text that says that no access to API. So we need to account such behavior in better error handling from our side or suggest that Vanderbilt return Http error instead of clear text.
