### ISSUE TITLE
PMD Day Measures disagree with TIN landing page

### ISSUE THREAD

**Issue by mbwatson** [RENCI/ctmd#86]
compare expected counts on https://trialinnovationnetwork.org/elements/trial-innovation-network-proposal-process/ with what is calculated on our dashboard.

@mbwatson will double-check logic

**Comment by mbwatson** [comment]
need to revisit to see if this is still an issue with the pipeline/sync keeping things updated.

**Comment by mbwatson** [comment]
@xu-hao I don't have access to the TIN dashboard, so can you see if this is something we still need to worry about, or has it been remedied through recent updates?

**Comment by krobasky** [comment]
I think we're past this now, but we do need to work through all the strange redcap data anamalies, as a team, and with Theresa. To that end, I've created a new lable, 'data anomaly' and tagged this ticket.
Other, similar tickets should be created and tagged. 
@LauraCapps when we have at least 6 tickets, let's add to the agenda a request to schedule a session with Theresa where we just go through them one-by-one with her people.

**Comment by xu-hao** [comment]
@mbwatson are you working on this?

**Comment by xu-hao** [comment]
will sit down with matt when he's back and log in and let him take a look

**Comment by mbwatson** [comment]
@xu-hao This is not something I am working on. I still don't have access to the TIN dashboard for comparison.

**Comment by xu-hao** [comment]
thanks @mbwatson

**Comment by xu-hao** [comment]
This can be closed, too.
