### ISSUE TITLE
Filter proposals by proposal id to display only the HEAL studies upon deployment

### ISSUE THREAD

**Issue by rajshruti18** [RENCI/ctmd#87]

**Comment by xu-hao** [comment]
Implemented pipeline to accept a file to contain a list of ids to retain in the transformed table

**Comment by dcarsey** [comment]
- [ ] Hao will fill it in here.

**Comment by krobasky** [comment]
set up heal-ctmd.renci.org
pulldown form github
start up docker
create username(s)
add pid's to the pipeline filter
test that only that data is seen by that user
(assign this ticket to Matt if competing prioirites get in the way

**Comment by xu-hao** [comment]
checked the boxes of items that are done

**Comment by krobasky** [comment]
I just got the heal-ctmd.renci.org server up with docker-compose working today. 
I'm trying to test the filtering but right now there's no data in the dashboard. I set up the sync from 'danger zone', @xu-hao How frequently does the redcap data get updated?
(can't close this until we get the data for HEAL: #142)

**Comment by xu-hao** [comment]
every day. you can use the sync button to update

**Comment by krobasky** [comment]
Oh - the sync button updates instantly?
It runs automatically 1xDay? Where can we adjust that to run more frequently?

**Comment by xu-hao** [comment]
No, it doesn't update instantly, it just put it on the queue. 

Yes.

Currently the frequency is hard coded. I can make it configurable.

**Comment by xu-hao** [comment]
Just saw new version of rq scheduler allows configurable frequency

**Comment by krobasky** [comment]
How hard would it be to make an 'update now' button, in the event that they make a change and want to pull it in right away?

@xu-hao can you make a ticket for that functionality, assign it to yourself, and label it with R1b, R1c, or R2 based on how hard it is and when you might have time to address it?

**Comment by xu-hao** [comment]
done

**Comment by xu-hao** [comment]
the sync button sends the job to the queue and run it immediately unless some other job is already running. do you want to have preemptive scheduling?

**Comment by krobasky** [comment]
This is all tested out and ready to go as soon as we get the proposal id's from Theresa.

**Comment by krobasky** [comment]
This is either done or obsolete
