### ISSUE TITLE
 Disable everything but the 'sites', 'proposals' menu items for HEAL

### ISSUE THREAD

**Issue by mbwatson** [RENCI/ctmd#88]

**Comment by krobasky** [comment]
Caveat - this should be a configurable option

Kimberly Robasky, PhD
RENCI
UNC, Chapel Hill
857-205-7843
________________________________

**Comment by krobasky** [comment]
Is there anybody that can help you with this, @mbwatson ?

**Comment by mbwatson** [comment]
this is simple, but I'm wondering if i've incorrectly stated the issue before understanding it completely. @krobasky clarify please: why would someone not want to view the HEAL studies themselves? isn't that the purpose of the HEAL-studies-only version of the application?

**Comment by krobasky** [comment]
@mbwatson I think the 'collaboration' and the 'landing' pages look a bit strange when there are only 2 studies, in fact the sankey diagram isn't even rendered - maybe because there's only 1 TIC.

Does it make sense to just disable those 2 pages?

**Comment by mbwatson** [comment]
I think the visualization components should decide what to show. What do you think, @davidborland ?

**Comment by davidborland** [comment]
I agree with @mbwatson , I think. May need some handling of special cases for this though.

**Comment by mbwatson** [comment]
we do not need to do this per 11/19/2019 call
