### ISSUE TITLE
Show enrollment per site on enrollment rate graph

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#92]
Show enrollment per site on enrollment rate graph, in addition to per study. 

The enrollment of a study is the aggregation across all sites.  NOW show the enrollment from each site.

**Comment by dcarsey** [comment]
Create an enrollment rate per site graph - - this is something we report to NIH regularly as well as to the sites (to try to create some healthy competition among sites to increase the enrollment rate)

**Comment by davidborland** [comment]
Related to #96

**Comment by davidborland** [comment]
Duplicate of #96
