### ISSUE TITLE
Display study metrics in a table across studies

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#93]
This will be specifically useful for the HEAL studies

**Comment by dcarsey** [comment]
One site may be in multiple studies, and wants to see how that site is doing across all studies, so if one site is underperforming so they can see if it’s doing better in other areas or doing poorly across all studies.

**Comment by mbwatson** [comment]
i think this is supposed to be titled "Display site metrics in a table across studies," which we already do
