### ISSUE TITLE
Show all donuts for each site on 1 page 

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#94]
e.g., “10 donuts”

**Comment by dcarsey** [comment]
Be able to display the site activation donut across studies (again specifically useful for the HEAL studies)

**Comment by davidborland** [comment]
Discussion with Kimberly and Dawn:

1. Instead of showing all donuts, use the sites page and add a horizontal bar for each site showing the current enrollment.
2. If a site is in multiple studies, show a bar per study
3. Enable sorting by best enrollment 
4. Enable grouping by study

**Comment by mbwatson** [comment]
@davidborland yeah that's a easy, clean way to do it

**Comment by davidborland** [comment]
Implemented site table with enrollment information and enrollment bar chart per site (per study)
