### ISSUE TITLE
Create a table for all 10  metrics to compare across studies.

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#95]
Add the following 10 columns to the 'Sites' table on the individual studies page (e.g., '/studies/{study-number}')

| Metric # | Column Name | Formula | Units |
| --------- | ---------------- | ------------ | -------------------- |
|1|“Protocol to FPFV”| FPFV - Reg Packet Sent| days |
|2|“Contract execution time”|Contract execution - Contract sent | days |
|3|“sIRB Approval time”|IRB Approval - IRB Submission| days |
|4|“Site open to FPFV”|FPFV - Site activation| days |
|5|“Site open to LPFV”|LPFV - Site activation| days |
|6|“Percent of consented patients randomized”|Patients enrolled /  Patients Consented| % |
|7|“Expected to expected ratio”|Patients enrolled / Patients Expected| % |
|8|“Ratio of randomized patients”|Patients Withdrawn / Patients enrolled| % |
|9|“Major Protocol deviations per randomized patients”|Protocol deviations/ Patients enrolled| % |
|10|“Queries per data elements”|Queries count / data element| % |

Some of these require additional columns to the 'study-sites' upload csv, namely:
 - __Lost to Follow Up__ for metric 8)
 - __Data Elements__ for metric 10

If it's easier, you can just add the metrics to the existing site drop-down panel instead of as a column in the sites table.
![image](https://user-images.githubusercontent.com/413166/101696504-34071a80-3a44-11eb-83e7-15bddfaa2f6d.png)

Close this ticket when:
 - [x] All columns have been added to the study-sites csv
 - [x] The 10 metric columns have been added to the 'sites' table on page /studies/<study-num>
 - [x] Rolled out to dev-pds beta tested by Kimberly or Dawn
 - [x] Deployed to stage-ctmd
 - [ ] new template for study-sites csv has been distributed to Jackie
 - [ ] Acceptance tested by Jackie
 - [ ] Deployed to ctmd, heal-ctmd
 - [ ] Deployment tested
 - [ ] Announced (e.g., tell Dawn, Kimberly, Jackie)

**Comment by dcarsey** [comment]
Be able to select a site (i.e. Duke University) and display metrics for that site in a table format across studies (this would be most useful for HEAL studies but would be interesting to see for non-HEAL studies as well)

**Comment by krobasky** [comment]
I have to format this description better

**Comment by luthfib** [comment]
Created a new ticket with the for the changes needed for the columns #350

**Comment by luthfib** [comment]
Metric number 7's name was changed to **Actual to expected randomized patient ratio**

**Comment by luthfib** [comment]
Metric number 8's name was changed to **Ratio of randomized patients that dropout of the study**
