### ISSUE TITLE
Add comparison of site enrollments across a study.

### ISSUE THREAD

**Issue by dcarsey** [RENCI/ctmd#96]
Consider a way to show where one site is compared to another site within a study (ideally when a site logs into a study they would be able to see on a graph where they are with enrollment compared to where other sites in the study are - - kind of a ‘you are here’ for the study)

**Comment by davidborland** [comment]
Currently we have the number of patients enrolled and the number of patients expected per site. There is a single value for each, i.e. no temporal information. Assuming this is the most up-to-date info, in alignment with the enrollment graphic, we could overlay that info on the enrollment graphic with something like this:

![EnrollmentGraphic_Sites_01](https://user-images.githubusercontent.com/289957/68142239-18564a00-fefd-11e9-8646-fb5d3bfbd89d.png)

Alternately, we could do something like this in a separate graphic, which makes it easier to show how they compare related to the target:

![EnrollmentGraphic_Sites_02](https://user-images.githubusercontent.com/289957/68142293-2f953780-fefd-11e9-9250-b97f31f78bb6.png)

**Comment by krobasky** [comment]
For Theresa: 
do you like these charts?
do you want traces for each site on the top graph? If so, can you give us the temporal info on the ED?

**Comment by davidborland** [comment]
Go with static bar chart visualization for now.
Potentially look at temporal information per site in the future.

**Comment by davidborland** [comment]
This information is now available in the sites list, and you can filter by study there.

Do we think that's enough for this feature, or do we also want to show this information in the study report page?

**Comment by davidborland** [comment]
Going to add the enrollment graphic to the site table in the study report. Enrollment numbers are already available, and exportable in CSV.

**Comment by davidborland** [comment]
Added enrollment bars to site table in study report.
